### PR TITLE
remove owner.email from our database & code

### PR DESCRIPTION
**Pull request by syphar**

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]
Is this something we never exposed publicly? r=me if so

**Comment by syphar** [comment]
> Is this something we never exposed publicly? r=me if so

@jyn514 jep, also we don't get it from the crates.io API any more. 

( I'm also removing the name, since we don't use that one)

**Comment by jyn514** [comment]
cc https://rust-lang.zulipchat.com/#narrow/stream/356853-t-docs-rs/topic/owner.20emails.3F

(btw @syphar, for changes that these that happen because of a zulip conversation, it would be very helpful for me if you could link the conversation so I know this has past discussion.)

**Comment by syphar** [comment]
> (btw @syphar, for changes like these that happen because of a zulip conversation, it would be very helpful for me if you could link the conversation so I know this has past discussion.)

Yeah, you're absolutely right.

**Pull request merged**
