### PR TITLE
Set navigation bar of rustdoc fixed

### PR DESCRIPTION
**Pull request by lzutao**
Make the navigation bar on top of the page fixed.
image

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
A little screenshot and an explanation about what changed please? :)

**Comment by lzutao** [comment]
@GuillaumeGomez Added.

**Comment by GuillaumeGomez** [comment]
It is how it was at first. I assume there is a reason why we changed this behavior.

**Comment by lzutao** [comment]
#186 changed it. But I don't see the rationale behind it.

**Comment by GuillaumeGomez** [comment]
I didn't even remember doing it. XD I personnaly prefer with the top bar fixed like done in your PR, but let's wait for @QuietMisdreavus and @onur's opinion on the topic.

**Comment by QuietMisdreavus** [comment]
Just to confirm, that screenshot is scrolled down a little? In other words, the top bar doesn't overlap the in-crate search box if you've scrolled all the way up on the page? I'm in favor of this, i just want to make sure it doesn't make the docs page more awkward to use.

**Comment by GuillaumeGomez** [comment]
It's back to what it was. But it also means that the docs page must have a margin top now, otherwise anchors will be under the fixed top bar.

**Comment by lzutao** [comment]
Yeah, I scrolled down that page a little bit then screenshotted it.

**Comment by lzutao** [comment]
Any suggestions to this changes?

**Comment by QuietMisdreavus** [comment]
I had a chance to test this a little bit more before deploying it, and it looks like it makes anything that's *not* a docs page shift up underneath the top bar:

image

image

image

I haven't deployed it yet, so i don't need to revert it immediately, but it's something i'd like to investigate before updating docs.rs on the server.

**Comment by GuillaumeGomez** [comment]
I'll quote myself. 😃 

> It's back to what it was. But it also means that the docs page must have a margin top now, otherwise anchors will be under the fixed top bar.

**Pull request merged**
