### PR TITLE
Show a consistent navbar across docs.rs and rustdoc pages

### PR DESCRIPTION
**Pull request by Nemo157**
Moves the docs.rs internal navbar links to the right-hand side, and keeps the crate-related navbar links when viewing the crate details/builds/source pages (while removing the dropdown that duplicates the crate details).

There is one remaining issue that I don't want to fix here; the "go to latest version" link doesn't appear on the non-rustdoc pages. The metadata used for rendering builds and source files doesn't currently pull enough details from the database for this, I think it might make the most sense to make both of them get the full `CrateDetails` and move the `is_latest_version` etc. checking into Tera helpers rather than being extra context variables, but that seems better done as a separate refactoring.

related to #1077 

Screenshots:

image

image

image

image

image

image

image

image

### CODE REVIEW

**Comment by jyn514** [comment]
I think I like this better. @jsha , @GuillaumeGomez , @Kixiron , what do you think?

**Comment by jsha** [comment]
This is great! I like the consistency across all pages. I have a small branch locally to give the About / Releases / Rust menus the same treatment we recently gave the crate / Source / Platform menus: Click to open and click to close rather than hover. I'll rebase on this branch once it lands.

**Comment by GuillaumeGomez** [comment]
I prefer this new one as well!

**Comment by jyn514** [comment]
@Nemo157 thanks for working on this!

**Pull request merged**
