### PR TITLE
Fix collecting github stats after timezone-migration

### PR DESCRIPTION
**Pull request by syphar**
this could be a quickfix for #1234

### CODE REVIEW

**Comment by syphar** [comment]
I need to check how to test this the best possible way

**Comment by syphar** [comment]
I were able to reproduce the error locally, and the change fixes it.

**Comment by syphar** [comment]
@pietroalbini  this could be a fix, but it doesn't add tests to the previously untested code. 

I'm not sure what the strategy for these tests will be (mocking? some other technique?), if that's decided I could provide tests in the next days. 

Question is if we want to wait with this fix for the tests.

**Comment by jyn514** [comment]
I don't think this should be blocked on tests, I see it as the same sort of issue as #822 where the tests need some design.

**Pull request merged**
