### PR TITLE
Ensure tests don't leak database connections

### PR DESCRIPTION
**Pull request by Nemo157**
Even if a pool instance is leaked (such as when the web server is leaked), internally drop the actual pool at the end of the test to ensure all connections are closed.

### CODE REVIEW

**Comment by jyn514** [comment]
I still can't run all tests because we leak file descriptors, but I guess there's not much to do about that ... ideally we'd switch to warp or hyper so this wasn't an issue :/

**Comment by Nemo157** [comment]
I might have fixed that when reducing the number of threads that the tests take, I could pull that commit into this PR too if you want?

**Comment by jyn514** [comment]
> I might have fixed that when reducing the number of threads that the tests take, I could pull that commit into this PR too if you want?

That would be great!

**Comment by jyn514** [comment]
This still leaks file descriptors for me :/ I guess if it fixes CI it's worth it, though.

```
thread 'r2d2-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 24, kind: Other, message: "Too many open files" }', /home/joshua/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/postgres-0.17.5/src/config.rs:322:14
```

**Comment by jyn514** [comment]
Oh wait, I forgot to set `ulimit -n 4096` first. Now it works :)

**Comment by jyn514** [comment]
r? @pietroalbini 

This seems ok to me, but I'm still a little hesitant about adding hacks on top of hacks when @Nemo157's been working on the warp switch: https://github.com/rust-lang/docs.rs/compare/master...Nemo157:warp-speed-iron

**Comment by Nemo157** [comment]
Yeah, it doesn't _stop_ leakage, but it does reduce it by a multiplier of something like 4*num_cpus.

The warp switch is going to take a _long_ time to finish, and all these hacks can be deleted once it's completed.

**Comment by pietroalbini** [comment]
I hate this, let's merge it :+1:

**Pull request merged**
