### PR TITLE
Support querying crate contents with cratename::some::path

### LINKED ISSUE #1531: Consider splitting crate name on spaces and `::`
Right now, `!drs tokio::spawn` takes you to https://docs.rs/tokio%3A%3Aspawn, which gives a 404. Ideally, duckduckgo would fix this on their end, but I looked at https://duckduckgo.com/newbang and they don't have any way to split the search string, only paste it literally. So it might be worth doing on our end instead and rewriting `/tokio::spawn` to https://docs.rs/tokio/?search=spawn.

### PR DESCRIPTION
**Pull request by joshtriplett**
This also makes searches on DuckDuckGo such as `!docsrs cratename::some::path` work.

Fixes #1531

### CODE REVIEW

**Comment by joshtriplett** [comment]
https://github.com/rust-lang/docs.rs/issues/1531

**Review by jyn514 — CHANGES_REQUESTED** [review]
This seems reasonable :) can you please add a test for both `tokio::spawn` and `tokio::runtime::Runtime`? Just that the redirect is correct, we don't need to assert anything about the search results. There are tests at the bottom of the file you can use as examples; you'll probably want the `assert_redirect` helper function too.

**Comment by Nemo157** [comment]
It'd also be good to have a test for something like `https://docs.rs/std::Future` since the sysroot crates have a custom redirect.

**Comment by jyn514** [comment]
@Nemo157 from my reading of the code, that isn't supported yet - @joshtriplett if you want to add it that's fine, but I won't block on it.

**Comment by joshtriplett** [comment]
Tests added. It looks like all the existing tests use mocked sample crates, so I followed that example.

**Review by jyn514 — CHANGES_REQUESTED** [review]
Ok, I tested and this doesn't actually do what we want. It's modifying the *search* handler on docs.rs itself. But our search handler already (mostly) supports this, it doesn't give a 404: 
image

what we actually want to modify is the top-level crate handler, which is what duckduckgo redirects to: https://docs.rs/quiche%3A%3Aconnection
image

**Comment by joshtriplett** [comment]
@jyn514 So, as far as I can tell, `!docsrs PLACEHOLDER` seems to be redirecting to `https://docs.rs/releases/search?query=PLACEHOLDER`, which is what I thought I modified. That was what I was trying to fix.

**Comment by Nemo157** [comment]
`!drs` and `!docsrs` are different (and personally I just type `docs.rs/foobar` directly since it's ~the same length, so I'd like it supported there).

**Comment by joshtriplett** [comment]
@Nemo157 Ah, interesting. That's an odd inconsistency in DDG.

**Comment by joshtriplett** [comment]
Added, plus tests; let's see if this works.

**Review by jyn514 — APPROVED** [review]

**Comment by joshtriplett** [comment]
Currently fixing a bug in this; new PR shortly.

**Comment by joshtriplett** [comment]
https://github.com/rust-lang/docs.rs/pull/1806

**Pull request merged**
