### PR TITLE
Add -Zrustdoc-scrape-examples to default Cargo args

### PR DESCRIPTION
**Pull request by willcrichton**
This PR adds `-Zrustdoc-scrape-examples` to the set of default arguments passed to `cargo doc`. This (finally!) enables the scrape-examples feature to be enabled by default for all readers of docs.rs. 

After extensive work within Cargo (rust-lang/cargo#10343, rust-lang/cargo#10533, rust-lang/cargo#10549, rust-lang/cargo#11430, rust-lang/cargo#11450), this option is now robust enough to avoid breaking any existing build. Any crate that documented before will still document with `-Zrustdoc-scrape-examples`. The core issue that was addressed is to not require dev-dependencies if they weren't already needed.

I have verified that `-Zrustdoc-scrape-examples` does not introduce breakage in a recent Crater run: <https://crater-reports.s3.amazonaws.com/scrape-examples/index.html>
(Note there are regressions, but they appear to be spurious and not related to the scrape-examples feature.)

~~This PR is currently a draft because I am waiting on rust-lang/cargo#11450 to reach nightly in a few days. But I wanted to put it up before then to provide room for discussion if someone is not comfortable enabling this flag.~~

cc @jyn514 @GuillaumeGomez @jsha

### CODE REVIEW

**Comment by willcrichton** [comment]
Now that https://github.com/rust-lang/rust/commit/fb0ca599cd9f2f1c972e38e1fb2a472d18aad629 has landed in nightly, this PR is ready for review.

**Comment by jyn514** [comment]
@willcrichton can you clarify for me where we ended up with the defaults? Is this bit still true? https://github.com/rust-lang/cargo/pull/10343#issuecomment-1027311704
> Packages have fine-grained control at the per-target level what's used as candidates for examples and what isn't (with the default being only the lib targets and examples)

If so, that seems good to me :) thank you for all your hard work pushing this feature through!

**Comment by willcrichton** [comment]
@jyn514 yes that's right. The longer explanation currently lives on the Unstable Features page in the Cargo book: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#scrape-examples

And thank you! Really excited to see this feature make it out in the world.

**Comment by syphar** [comment]
@jyn514 so this can be approved & merged?

**Comment by jyn514** [comment]
Yup!

**Pull request merged**
