### PR TITLE
upgrade gix, moka, lol_html

### PR DESCRIPTION
**Pull request by syphar**
- https://github.com/cloudflare/lol-html/releases/tag/v0.4.0
- https://github.com/moka-rs/moka/blob/master/CHANGELOG.md#version-0110

gix, the ones with breaking changes (but it probably doesn't matter): 
- https://github.com/Byron/gitoxide/releases/tag/gix-v0.38.0
- https://github.com/Byron/gitoxide/releases/tag/gix-v0.40.0
- https://github.com/Byron/gitoxide/releases/tag/gix-v0.44.0

### CODE REVIEW

**Review by Nemo157 — APPROVED** [review]

**Comment by Nemo157** [comment]
Actually, would it be better to keep `gix` in sync with `crates-index-diff` to avoid duplicates?

**Comment by syphar** [comment]
valid point, IMO I would rather just update crates-index-diff itself :) 

Actively managing dependencies of dependencies in someones head seems like a hard problem "only" for compile-times. 

Or am I forgetting anything?

**Comment by syphar** [comment]
https://github.com/Byron/crates-index-diff-rs/pull/37

**Comment by Nemo157** [comment]
Ah, it's only a build dependency anyway, so probably won't affect compile times, at runtime we use the re-exported version from `crates-index-diff`.

**Pull request merged**
