### PR TITLE
drop length limitation for crate name & version

### PR DESCRIPTION
**Pull request by syphar**
this fixes [this sentry error](https://rust-lang.sentry.io/issues/5302037253/?environment=production&project=5499376&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=7): 
> error trying to add rraaaaaaaaaaaaaaah-0.8.1+dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddexecrmrfzstd.1.5.0 to build queue
> 
> Error
db error: ERROR: value too long for type character varying(100)

From what I see, crates.io uses a plain `VARCHAR` without any length restrictions, I don't see why we can't do the same.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Can you add a test please?

**Comment by syphar** [comment]
> Can you add a test please?

done

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Please merge once clippy is happy.

**Pull request merged**
