### PR TITLE
Refactor queries to use the more semantic postgres::Client methods

### PR DESCRIPTION
**Pull request by Nemo157**

### CODE REVIEW

**Comment by Nemo157** [comment]
(I'm sure touching almost every database query is unlikely to conflict with other merge requests 🤭)

**Comment by jyn514** [comment]
I'm really uncomfortable making changes like this without https://github.com/rust-lang/docs.rs/issues/874. The new code is definitely better - but are we sure all of it is tested? Changes like this have been a major source of outages in the past.

This is the same reason I don't want to refactor the builder too much until we have https://github.com/rust-lang/docs.rs/issues/822.

**Comment by Nemo157** [comment]
(I'm planning to go through this and cherry-pick out all the changes that are covered in existing tests, just got distracted from finishing it on Sunday).

**Comment by Nemo157** [comment]
(superseded by moving to sqlx soon)

**Pull request closed without merging**
