### PR TITLE
Fix footer positionning

### LINKED ISSUE #1382: Footer styling broken on search page
On the search results page (for any crate) the page's footer displays in the middle of and underneath the search results:
An example can be seen [here](https://docs.rs/sqlx/0.5.2/sqlx/macro.query_as.html?search=Error):
Screenshot from 2021-04-29 01-27-05 (Note: this happens regardless of screen size/ratio)

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #1382.

Follow-up of #1367

### CODE REVIEW

**Review by Nemo157 — APPROVED** [review]
Tested on new docs locally, fixes search page and footer not being at the bottom on short rustdoc pages. Can't easily test against old doc builds till it's deployed.

**Comment by GuillaumeGomez** [comment]
`src/docbuilder/rustwide_builder.rs:730` is failing. Does someone knows why?

**Comment by syphar** [comment]
> `src/docbuilder/rustwide_builder.rs:730` is failing. Does someone knows why?

it seems like it is: 
> `error: component 'rustfmt' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel nightly`

So in any case unrelated to the style changes.

**Comment by GuillaumeGomez** [comment]
Good then, let's merge!

**Comment by jyn514** [comment]
@syphar could we separate "slow tests" and "fast tests" into different github checks? That would make it more clear that the unit tests are still passing.

I wonder if we could also change CI to try and install an older version of nightly if rustfmt isn't available. Or just disable rustfmt for the test image in the first place. https://github.com/rust-lang/rust/issues/82385 is a better long term solution for this but in the meantime ...

**Comment by syphar** [comment]
> @syphar could we separate "slow tests" and "fast tests" into different github checks? That would make it more clear that the unit tests are still passing.

definitely possible, I'll look into it. 


> I wonder if we could also change CI to try and install an older version of nightly if rustfmt isn't available. Or just disable rustfmt for the test image in the first place. [rust-lang/rust#82385](https://github.com/rust-lang/rust/issues/82385) is a better long term solution for this but in the meantime ...

I'll have to dig into where that is done, if I find it I'll update it :)

**Comment by jyn514** [comment]
> I'll have to dig into where that is done, if I find it I'll update it :)

Hmm, it should already be working, it must have broken at some point: https://github.com/rust-lang/docs.rs/blob/e85bfdf26ffb7a51536b4c57e3bd4fdcb988ea44/src/docbuilder/rustwide_builder.rs#L131-L143

**Comment by jyn514** [comment]
Yeah no that error is unrelated to why the build failed:
```
 [2021-04-29T09:42:28Z WARN  docs_rs::docbuilder::rustwide_builder] failed to install rustfmt: unable to add component rustfmt for toolchain nightly via rustup
[2021-04-29T09:42:28Z INFO  docs_rs::docbuilder::rustwide_builder] continuing anyway, since this must be the first build
```

**Comment by syphar** [comment]
> > I'll have to dig into where that is done, if I find it I'll update it :)
> 
> Hmm, it should already be working, it must have broken at some point:

perhaps it's only fixed for _updating_ the toolchain, not the initial install? 

Anyway, I'll try to find something

**Comment by syphar** [comment]
hm.. strange. In any case, the build cannot fail because of the styling (right?),  so for this PR we're fine.

**Comment by jyn514** [comment]
Right, it also failed on https://github.com/rust-lang/docs.rs/pull/1384.

**Pull request merged**
