### PR TITLE
[WIP] switch to cargo_metadata instead of rewriting it

### PR DESCRIPTION
**Pull request by jyn514**
This doesn't work at all, but opening a PR so I don't forget to come back to it.

See https://github.com/serde-rs/json/issues/727 for the motivation.

### CODE REVIEW

**Comment by jyn514** [comment]
I want to resolve https://github.com/rust-lang/cargo/issues/8880 one way or another before working on this more.

**Comment by Nemo157** [comment]
I see `homepage` and `documentation` in the `cargo metadata` output, is it just that `cargo-metadata` doesn't include it in its data structure?

**Comment by jyn514** [comment]
:facepalm: I was testing with stable, not nightly - I guess the behavior is invisibly different? That seems like a footgun.

**Comment by jyn514** [comment]
This is currently blocked on https://github.com/oli-obk/cargo_metadata/issues/158.

**Comment by jyn514** [comment]
https://github.com/rust-lang/team/pull/1051

**Pull request closed without merging**
