### PR TITLE
Fix position of navbar sub menu items

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/docs.rs/issues/1810.

### CODE REVIEW

**Review by Nemo157 — APPROVED** [review]
Works fine on https://docs.rs.dev.nemo157.com

**Comment by GuillaumeGomez** [comment]
Thanks for uploading it and testing it!

**Comment by GuillaumeGomez** [comment]
Merging then!

**Comment by syphar** [comment]
@GuillaumeGomez from what I remember,  @jyn514 ( and also me) prefer linear history, so we typically do rebase-merges.

**Comment by GuillaumeGomez** [comment]
Oh sorry. Noted for next time. Also: can it be forced in the project settings by any chance?

**Comment by syphar** [comment]
> Oh sorry. Noted for next time. Also: can it be forced in the project settings by any chance?

yeah, this can be configured

**Comment by GuillaumeGomez** [comment]
Cool! Just need someone to do it now. :laughing:

**Pull request merged**
