### PR TITLE
fix changing versions not keeping the paths

### LINKED ISSUE #2349: Changing versions doesn't stay on same item
Steps to reproduce:

1. Visit https://docs.rs/rustls/latest/rustls/struct.ConfigBuilder.html
2. Click the crate name in the topbar to open the menu
3. Select a different version (e.g. 0.21.9)

Expected result:

Wind up on https://docs.rs/rustls/0.21.9/rustls/struct.ConfigBuilder.html, that is, the same page in a different version.

Actual result:

Wind up on https://docs.rs/rustls/0.21.9/rustls/index.html, the index page.

### PR DESCRIPTION
**Pull request by syphar**
This is a regression from #2113 , fixes #2349 

This fix here is mostly copying logic from the `get_all_platforms_inner` method in this module. 

I'm seeing that plenty of logic around version-matching is duplicated between handlers, and will try to find a way to refactor this. Also the URL-Patterns for the target-redirect lead to the handler itself being quite complex, perhaps we could just use GET parameters there. ( also separate IMO).

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks for the fix. Agreed, a lot of logic is duplicated in a few places, would be nice to centralize it. Also please add a test to prevent this regression from happening again.

**Comment by syphar** [comment]
> Thanks for the fix. Agreed, a lot of logic is duplicated in a few places, would be nice to centralize it. Also please add a test to prevent this regression from happening again.

Interesting, that handler didn't have _any_ tests before :) 

I'll add some

**Comment by syphar** [comment]
( forget it, found the existing tests)

**Comment by syphar** [comment]
@GuillaumeGomez I added a short test for the partial

**Comment by GuillaumeGomez** [comment]
Looks all good to me, thanks!

**Pull request merged**
