### PR TITLE
Document that time extensions will be limited to one target

### PR DESCRIPTION
**Pull request by jyn514**
Thought of this in https://github.com/rust-lang/docs.rs/issues/1001, it seems like a good policy.
r? @pietroalbini

### CODE REVIEW

**Comment by jyn514** [comment]
image

**Comment by Kixiron** [comment]
If we're going to have a policy, then a method of "enforcement" should probably be implemented because there's nothing stopping someone from getting an increase and then switching to a higher number of targets later on (either forgetting that they have an increase or maliciously)

**Comment by jyn514** [comment]
Actually this can be enforced in a database constraint too, let me do that.

**Comment by jyn514** [comment]
@Kixiron there is already a way to enforce it: `update sandbox_overrides set max_targets = 1 where timeout_seconds is not null;`. But that requires manual action - if I add a database constraint I can't forget to run that command.

**Comment by pietroalbini** [comment]
I wouldn't put a hard constraint on the database schema. What we *could* do is change the limits code so that when the number of targets is not overridden, it defaults to `n` when the timeout is not overridden and to `1` when it is.

**Comment by Kixiron** [comment]
I think displaying to the user on the builds page that their builds are limited is important too if we aren't

**Comment by jyn514** [comment]
> I think displaying to the user on the builds page that their builds are limited is important too if we aren't

We already do: https://docs.rs/crate/haxcel/0.1.0/builds

**Comment by Kixiron** [comment]
I mean specially limited, like in the situation where we extend build time in exchange for a single target (only if we don't already)

**Comment by jyn514** [comment]
Do you think that's necessary? We already document the effective limits build page and the policy on /about/builds. Putting in on a successful build seems like overkill.

**Comment by Kixiron** [comment]
I mean on a crate-by-crate basis, if I own the crate `foo-bar-baz` and I get time extended, when I look at my builds page I should see
| Limit | Setting |
| :- | :-: |
| Maximum rustdoc execution time | 10 hours |
| Maximum number of build targets | 1 |

**Comment by jyn514** [comment]
That's what it says already, that's the link I gave.

**Comment by jyn514** [comment]
The limits for that page are calculated the same way they're calculated for builds, they don't show exactly what's in the database.

**Comment by jyn514** [comment]
@pietroalbini is this waiting on anything?

**Comment by pietroalbini** [comment]
Looks good to me.

**Pull request merged**
