### PR TITLE
use different crate for cross-compile non-host default test

### PR DESCRIPTION
**Pull request by syphar**
I tried to find a different example to be used via: 
```
select
distinct crates.name

from
releases,
crates

where
releases.crate_id = crates.id and
default_target = 'i686-pc-windows-msvc' and
doc_targets::jsonb ? 'x86_64-unknown-linux-gnu'

order by crates.name;
```

Which only gave me **2** results, the now yanked crate, and this one.

### CODE REVIEW

**Comment by syphar** [comment]
( I'm waiting for the tests to pass) 

@jyn514 does the query represent what should be the test-crate for this test?

**Comment by syphar** [comment]
@jyn514 the tests fails, and I don't know enough about the build-process or cross-compiling to know if the build is wrong, or the example .. sorry I couldn't get further

**Comment by jyn514** [comment]
```
where
releases.crate_id = crates.id and
default_target = 'i686-pc-windows-msvc' and
doc_targets::jsonb ? 'x86_64-unknown-linux-gnu'
```
this is unnecessarily restrictive - you just need `default_target != 'x86_64-unknown-linux-gnu'`

**Comment by jyn514** [comment]
@syphar looks like the database entry for this crate doesn't match what it has configured in Cargo.toml - maybe a bug we fixed? https://docs.rs/crate/misdreavus-test/latest/source/Cargo.toml.orig
I'd suggest finding a different crate with the less restrictive query.

**Comment by syphar** [comment]
@jyn514 I found a crate that passed :) can you check if it actually fulfills the requirements?

**Review by jyn514 — APPROVED** [review]

**Pull request merged**
