### PR TITLE
Fix resize of top navbar

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Here what the issue looks like:

Screenshot from 2022-01-22 12-07-51

Once fixed it looks like this:

Screenshot from 2022-01-22 12-31-17

### CODE REVIEW

**Review by syphar — COMMENTED** [review]
When I try a newer package I cannot reproduce the problem, is this still the right place to fix it? 

examples: 
- https://docs.rs/serde_json/1.0.76/serde_json/ (recent release, doesn't seem to have this problem?) 
- https://docs.rs/itertools/0.10.3/itertools/index.html here I can see the failure

**Comment by GuillaumeGomez** [comment]
I can reproduce it on the serde_json you provided:

https://user-images.githubusercontent.com/3050060/150650884-8d0f6780-f55e-4278-a77a-e2f6da433a79.mp4

It's when reducing the screen width at a precise spot (like usual).

**Comment by syphar** [comment]
Yeah, you're right. On another computer I can reproduce it now (same OS & Browser & version). 

Anyways. Manual test of the fix is fine. 

Can someone review the code-change itself? @Nemo157 ? Or @jsha ?

**Comment by Nemo157** [comment]
I seem to still have the issue on <https://docs.rs.dev.nemo157.com/dialectic-tokio-serde/0.1.0/dialectic_tokio_serde/>, I've checked the css in FF devtools and it definitely has the new media-query sizes.

**Comment by GuillaumeGomez** [comment]
Ok, I think I understand the problem: we need to set a maximum width to the crate name in the topbar. I'll do it in this PR too.

**Comment by Nemo157** [comment]
I'm pretty sure we already do, that's a crate that exceeds it and gets `...` applied which is why I have it there as a testcase.

**Comment by GuillaumeGomez** [comment]
Then we don't have the right sizes. Let me check in any case and if needed I'll update the values. Thanks for the feedback!

**Comment by GuillaumeGomez** [comment]
I took the biggest possible case this time to ensure it was working in all cases.

**Comment by Nemo157** [comment]
This seems to fix it now in responsive design mode, but not when I actually resize my firefox window. I think it might not be taking the scrollbar width into account for windows that actually have scrollbars instead of overlays?

**Comment by GuillaumeGomez** [comment]
@Nemo157 Sorry I don't understand. Do you have a screenshot with the issue please?

**Comment by Nemo157** [comment]
Screenshot by manually shrinking the window (this is with `window.innerWidth = 924` and `document.body.clientWidth = 907`, because of the 17px wide scrollbar):

image

vs screenshot using responsive design mode (giving `window.innerWidth = 919` and `document.body.clientWidth = 919`)

image

AFAICT after a little searching it's literally impossible to deal with the scrollbar width in css, the only solution would be to use JS to actually measure the width, or use a hardcoded offset of the max scrollbar width you will support. (Maybe @jsha has some other ideas? I am not at all a webdev anymore so I could be missing some new tricks 😁).

**Comment by GuillaumeGomez** [comment]
Oh I see! Well then let's just always take the scrollbar in account. :)

**Comment by GuillaumeGomez** [comment]
I added 6px in both sizes to take the sidebar into account.

**Review by Nemo157 — APPROVED** [review]

**Pull request merged**
