### PR TITLE
robots: block semver-based URLs

### PR DESCRIPTION
**Pull request by jsha**
Part of #1438

### CODE REVIEW

**Comment by jaskij** [comment]
Google has opensourced their [parsing and matching C++ library](https://github.com/google/robotstxt). They also include a [CLI program](https://github.com/google/robotstxt/blob/master/robots_main.cc) to check if specific URL is allowed or not.

Having tested with it, the change does not seem to work:

```
$ ./robots robots.txt - https://docs.rs/tokio-postgres/0.7.7/tokio_postgres/index.html
user-agent '-' with URI 'https://docs.rs/tokio-postgres/0.7.7/tokio_postgres/index.html': ALLOWED
$ ./robots robots.txt - https://docs.rs/tokio-postgres/\^0.7.7/tokio_postgres/index.html
user-agent '-' with URI 'https://docs.rs/tokio-postgres/^0.7.7/tokio_postgres/index.html': ALLOWED
$ ./robots robots.txt - https://docs.rs/tokio-postgres/\~0.7.7/tokio_postgres/index.html
user-agent '-' with URI 'https://docs.rs/tokio-postgres/~0.7.7/tokio_postgres/index.html': ALLOWED
```

If there's a need, I could probably whip up a tool that goes over a file and checks if a URL is allowed or not, or however you'd want this done.

**Comment by syphar** [comment]
> Google has opensourced their [parsing and matching C++ library](https://github.com/google/robotstxt). They also include a [CLI program](https://github.com/google/robotstxt/blob/master/robots_main.cc) to check if specific URL is allowed or not.

There seems to be [a rust port of that library](https://docs.rs/robotstxt/latest/robotstxt/), which means we could write unit-tests for it.

**Comment by jsha** [comment]
Ooh thanks for finding that tool and checking. I tried a few different revisions against https://technicalseo.com/tools/robots-txt/. There seem to be two problems:

 - I hadn't specified `User-Agent: *`
 - For some reason `Disallow: */^` wasn't resulting in disallowing the URL we wanted to block. But `Disallow: *^` does. I'm not sure why they are treated differently. But for now I've uploaded a new version with `Disallow: *^`.

**Comment by jaskij** [comment]
> There seems to be [a rust port of that library](https://docs.rs/robotstxt/latest/robotstxt/), which means we could write unit-tests for it.

Thing is, that port is three years old, and doesn't seem to be maintained. Whether it's up to date with what Google is doing is anyone's guess.

While it's non-ideal, I'd much rather pull Google's code and write a Rust program that executes their CLI - at least this way it can be up-to-date. Assuming the CI is even set up for building C++ code. From a quick look, there are only two dependencies, both downloaded from source at build time.

Both options require some work and it's very much a pick your poison situation.

**Comment by syphar** [comment]
> > There seems to be [a rust port of that library](https://docs.rs/robotstxt/latest/robotstxt/), which means we could write unit-tests for it.
> 
> Thing is, that port is three years old, and doesn't seem to be maintained. Whether it's up to date with what Google is doing is anyone's guess.

I just re-ran their tests (which run [the tests from the google original library](https://github.com/google/robotstxt/blob/86d5836ba2d5a0b6b938ab49501be0e09d9c276c/robots_test.cc) with the rust fork), and they still pass. 
So I think we might be fine, of course assuming everything is covered by tests also in the google library.

**Comment by jaskij** [comment]
> > > There seems to be [a rust port of that library](https://docs.rs/robotstxt/latest/robotstxt/), which means we could write unit-tests for it.
> > 
> > 
> > Thing is, that port is three years old, and doesn't seem to be maintained. Whether it's up to date with what Google is doing is anyone's guess.
> 
> I just re-ran their tests (which run [the tests from the google original library](https://github.com/google/robotstxt/blob/86d5836ba2d5a0b6b938ab49501be0e09d9c276c/robots_test.cc) with the rust fork), and they still pass. So I think we might be fine, of course assuming everything is covered by tests also in the google library.

If that's the case, it would make sense to incorporate it, true. Maybe make sure `robots_test.cc` is up to date, but otherwise I don't think there are any objections.

> ( I might have missed an implementation / compilation detail, my C++ (and specifically cmake/make) times are very long ago)

I don't think so, but I also haven't looked closely at stuff. Do note that `robots_test.cc` is slightly different between the two projects, on account on linking against the Rust library to actually run the tests. Bot otherwise, it all seems good to me. Feel free to ping me if there are any issues with the CMake/C++ part, my skills in both are quite current.

**Comment by jsha** [comment]
I downloaded and built the official [Google robots checker](https://github.com/google/robotstxt) linked above, and tested it with `Disallow: */^`. 

Turns out that _does_ work correctly, so long as I specify `User-Agent: *`. I think the third-party site I [checked with last night](https://github.com/rust-lang/docs.rs/pull/2695#issuecomment-2556359478) was misleading.

```
$ cat ~/docs.rs/static/robots.txt
Sitemap: https://docs.rs/sitemap.xml
# Semver-based URL are always redirects, and sometimes
# confuse Google's duplicate detection, so we block crawling them.
# https://docs.rs/about/redirections
User-Agent: *
Disallow: */^
Disallow: */~
$ ./robots ~/docs.rs/static/robots.txt Googlebot 'https://docs.rs/tokio-postgres/^0.7.7/tokio_postgres/index.html'
user-agent 'Googlebot' with URI 'https://docs.rs/tokio-postgres/^0.7.7/tokio_postgres/index.html': DISALLOWED
$ ./robots ~/docs.rs/static/robots.txt Googlebot 'https://docs.rs/tokio-postgres/~0.7.7/tokio_postgres/index.html'
user-agent 'Googlebot' with URI 'https://docs.rs/tokio-postgres/~0.7.7/tokio_postgres/index.html': DISALLOWED
```

**Comment by syphar** [comment]
> I downloaded and built the official [Google robots checker](https://github.com/google/robotstxt) linked above, and tested it with `Disallow: */^`.
> 
> Turns out that _does_ work correctly, so long as I specify `User-Agent: *`. I think the third-party site I [checked with last night](https://github.com/rust-lang/docs.rs/pull/2695#issuecomment-2556359478) was misleading.
> 
> ```
> $ cat ~/docs.rs/static/robots.txt
> Sitemap: https://docs.rs/sitemap.xml
> # Semver-based URL are always redirects, and sometimes
> # confuse Google's duplicate detection, so we block crawling them.
> # https://docs.rs/about/redirections
> User-Agent: *
> Disallow: */^
> Disallow: */~
> $ ./robots ~/docs.rs/static/robots.txt Googlebot 'https://docs.rs/tokio-postgres/^0.7.7/tokio_postgres/index.html'
> user-agent 'Googlebot' with URI 'https://docs.rs/tokio-postgres/^0.7.7/tokio_postgres/index.html': DISALLOWED
> $ ./robots ~/docs.rs/static/robots.txt Googlebot 'https://docs.rs/tokio-postgres/~0.7.7/tokio_postgres/index.html'
> user-agent 'Googlebot' with URI 'https://docs.rs/tokio-postgres/~0.7.7/tokio_postgres/index.html': DISALLOWED
> ```

Should we also test of our other URLs still pass? I don't know too much about robots.txt syntax and if (for example) `^` or `~` need to be escaped? 


Apart from that I'm fine with the change. 

General question for the deploy: do you feel that this should be watched after deploy? Can you watch the search console for this the next (= christmas) week? Otherwise I would postpone the deploy until there is time to watch the console.

**Review by syphar — APPROVED** [review]

**Comment by jsha** [comment]
> do you feel that this should be watched after deploy? Can you watch the search console for this the next (= christmas) week? Otherwise I would postpone the deploy until there is time to watch the console.

Yeah, mainly I'd want to check to see if the URLs actually got blocked. The effect should be pretty quick, as soon as robot.txt is fetched next (about 24 hours). I'm happy to check in periodically over the next week.

**Pull request merged**
