### PR TITLE
Remove pubsub integration

### PR DESCRIPTION
**Pull request by jyn514**
Pubsub was never used to my knowledge, and made the queue builder more complicated.
This:
- Removes pubsub integration
- Changes `QueueInProgress` to no longer track how many crates were
  built since the last pubsub update
- Fixes a couple typos
- Makes the `BuilderState` enum much simpler

In particular, the queue builder is no longer doing network IO, so it's
less likely anything can go wrong outside of a build.

r? @pietroalbini
cc https://github.com/rust-lang/docs.rs/pull/120

### CODE REVIEW

**Comment by jyn514** [comment]
Oh, and this also fixes a bug where an error building a crate would freeze the whole queue for 60 seconds (since it would remain in whatever state it had before rather than calling `increment`).

**Comment by syphar** [comment]
@jyn514 should I look into this? Or do you want to wait for @pietroalbini ?

**Comment by jyn514** [comment]
@syphar I think pietro is busy, if you have time I'd love a review :)

**Review by syphar — APPROVED** [review]
code change looks good, 

I ran a short local test which looked like the queue picked up new releases correctly

**Pull request merged**
