### PR TITLE
Rename crates to be in the same top-level crates/ directory

### PR DESCRIPTION
**Pull request by jyn514**
Unblocks https://github.com/rust-lang/docs.rs/pull/1033.
r? @pietroalbini

### CODE REVIEW

**Comment by Nemo157** [comment]
Whats wrong with having them at the root? Outside `rust-lang/rust` (because of its ridiculously high number of crates) adding in an extra level of nesting is uncommon.

**Comment by pietroalbini** [comment]
I feel like we're reaching a point where there is too much going on in the root directory, especially as we add more standalone crates (docsrs-metadata, badge, font-awesome-as-a-crate, a possible future archive crate...).

**Comment by jyn514** [comment]
> adding in an extra level of nesting is uncommon.

If it helps, it's the same number of nesting as normal because there's no `src/` directory (I don't like those at _all_ in shared crates). This also gives them a common `crates/` prefix - before you couldn't tell `metadata` was a crate from the name. Changing it to `docsrs-metadata` in the top-level is also possible but not as appealing to me.

**Comment by Nemo157** [comment]
> If it helps, it's the same number of nesting as normal because there's no src/ directory (I don't like those at all in shared crates).

Another thing I find really weird about this setup, and breaks my muscle memory for editing files from sibling crates :grin:; but I don't have any major issues with this setup, most workspaced projects seem to grow some weird unique setup eventually.

**Pull request merged**
