### PR TITLE
Add `optional` suffix to dependency

### PR DESCRIPTION
**Pull request by linyihai**
Addressed https://github.com/rust-lang/docs.rs/issues/2397

Add `optional` suffix to dependency.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Looks good to me. Please add a test.

**Comment by linyihai** [comment]
> Looks good to me. Please add a test.

The test case was appended to the last commit.

**Comment by linyihai** [comment]
The test stuck in the GUI_test for a long time.

**Comment by GuillaumeGomez** [comment]
Restarted the GUI test job.

**Review by syphar — APPROVED** [review]
Thank you for this improvement! 

I did a manual test, and taking the `fs-err` example it looks like this: 
grafik

I feel like the structure could be improved by having a visual distinction between the dependency groups and the "optional" test, but IMO it's fine for now.

**Comment by linyihai** [comment]
> I feel like the structure could be improved by having a visual distinction between the dependency groups and the "optional" test, but IMO it's fine for now.

Thank you for review this.  I am not very good at visual design, if there is a clear design scheme, I am willing to try to improve it.

**Pull request merged**
