### PR TITLE
Add crates.js and woff2 fonts to required files

### PR DESCRIPTION
**Pull request by dtolnay**
Attempt at #1300. Untested, but guessing based on #894 and #1109.

### CODE REVIEW

**Review by jyn514 — COMMENTED** [review]
Thanks! Do you mind adding `FireSans-Medium.woff2` and `FireSans-Regular.woff2` while you're at it? They'd go under `ESSENTIAL_FILES_UNVERSIONED`.

**Comment by dtolnay** [comment]
Done!

**Comment by jyn514** [comment]
Thanks!

**Comment by jsha** [comment]
This looks correct to me. Thanks for fixing!

**Pull request merged**
