### PR TITLE
Remove unused `staticfile` dependency

### PR DESCRIPTION
**Pull request by jyn514**
~~Should help address https://github.com/rust-lang/docs.rs/issues/656~~ Nope.

r? @pietroalbini

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
We might also want to add a cache header to the static files -- to avoid requests from CloudFront -- but I suspect that can be handled later. (Previously, the staticfile crate did set ETag and Last-Modified on our end).

https://github.com/iron/staticfile/blob/0.4.0/src/static_handler.rs#L212-L214

Otherwise, this looks good to me, though I don't know what our process these days is for merging -- r=me :)

**Comment by jyn514** [comment]
I think we do that already, actually: https://github.com/rust-lang/docs.rs/blob/master/src/web/file.rs#L25

> I don't know what our process these days is for merging -- r=me :)

We don't really have a process ... I don't have admin access to the repo so I can't turn on protected branches.

**Comment by Mark-Simulacrum** [comment]
Please also update the Dockerfile to not touch public_html.

**Comment by Mark-Simulacrum** [comment]
Looks like tests are failing, but feel free to merge whenever.

**Comment by jyn514** [comment]
After testing locally, it looks like this breaks something with the favicon. I don't feel comfortable merging this until we figure out what's going on there.

**Pull request closed without merging**
