### PR TITLE
Handle panics in `build_next_queue_package`

### PR DESCRIPTION
**Pull request by jyn514**
Previously, these would cause the builder to loop forever. Now, it locks
the queue until someone has a chance to look at it.

Fixes https://github.com/rust-lang/docs.rs/issues/382.

### CODE REVIEW

**Comment by pietroalbini** [comment]
This looks fine, but we should then have a metrics that outputs 0 if the queue is locked. That way we can alert when this happens.

**Comment by jyn514** [comment]
This got kind of big - happy to split it out into smaller PRs if you like.

**Review by Nemo157 — APPROVED** [review]

**Comment by jyn514** [comment]
Oh oops, I forgot to push the commit adding the metrics. I'll try and get to it this week.

**Comment by jyn514** [comment]
> Oh oops, I forgot to push the commit adding the metrics. I'll try and get to it this week.

Nope, I just named the commit horribly :facepalm: fixed in the latest push.

I'm going to go ahead and merge this since @Nemo157 already approved it - thanks for taking a look!

**Pull request merged**
