### PR TITLE
Give focus to rustdoc main content if available

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Users will be able to scroll again on the content!

### CODE REVIEW

**Comment by jyn514** [comment]
I can't replicate this fix locally, I still can't scroll up or down without clicking on the main window. My firefox install is pretty buggy in general though, can someone else test this out?

**Comment by GuillaumeGomez** [comment]
I picked the upper level element (both works in my case but maybe this one will work in your case as well?).

**Comment by Koxiaet** [comment]
I also encountered this problem but added a different fix - [510](https://github.com/rust-lang/docs.rs/pull/510). Perhaps this one will work better.

**Comment by jyn514** [comment]
Closing in favor of #579

**Pull request closed without merging**
