### PR TITLE
Redirect docs.rs/std to the official standard library docs.

### PR DESCRIPTION
**Pull request by m-ou-se**
See also #56 and #193.

### CODE REVIEW

**Comment by m-ou-se** [comment]
Is there anything that needs to be done or discussed before this can be merged?

**Comment by GuillaumeGomez** [comment]
The problem with this PR is that it doesn't take into account the version of the std used when documenting the crate. Could you update the url to match it like `https://doc.rust-lang.org/{version}/std/` please? So for example: `https://doc.rust-lang.org/1.29.0/std/`.

**Comment by m-ou-se** [comment]
> The problem with this PR is that it doesn't take into account the version of the std used when documenting the crate.

When documenting which crate? I'm not sure I understand your comment. I just want `docs.rs/std` to redirect to the latest std documentation at `doc.rust-lang.org/std`, because the first url is easier to remember and type. All generated documentation would still directly link to `doc.rust-lang.org/{version}/...`.

**Comment by GuillaumeGomez** [comment]
From what I understand of [your code](https://github.com/rust-lang/docs.rs/pull/398/files#diff-db933256db133927163e75c554ffdfb6R71), it doesn't take the version into account. For example, if the item being linked doesn't exist anymore in the current std lib, then you'd end up with a dead link.

**Comment by m-ou-se** [comment]
Which items? All it does is redirect `docs.rs/std` to `doc.rust-lang.org/std`, nothing else. It doesn't link to specific items.

**Comment by GuillaumeGomez** [comment]
Oh my bad, I completely misunderstood what your PR was doing... Just one thing then, can you replace the current url with `doc.rust-lang.org/stable/std` please?

**Comment by m-ou-se** [comment]
Sure, done!

**Comment by pietroalbini** [comment]
The redirect is in place! https://docs.rs/std

**Pull request merged**
