### PR TITLE
Disable per-crate search now that rustdoc bugs are fixed

### PR DESCRIPTION
**Pull request by jyn514**
Follow up to https://github.com/rust-lang/docs.rs/pull/497,
https://github.com/rust-lang/rust/pull/76052

r? @GuillaumeGomez, but shouldn't be merged until the next nightly is published and I have a chance to post screenshots.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:tada:

**Comment by jyn514** [comment]
image

**Comment by jyn514** [comment]
@GuillaumeGomez should I count the 🎉 as an approval? ;)

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
You now have my "official" approval. :p

**Pull request merged**
