### PR TITLE
upgrade `semver`

### PR DESCRIPTION
**Pull request by syphar**
<https://github.com/dtolnay/semver/compare/0.9.0...1.0.4>

```bash
 cargo upgrade semver
docs-rs:
    Upgrading semver v0.9 -> v1.0.4
```

### CODE REVIEW

**Comment by syphar** [comment]
r? @Nemo157  

I didn't find a good changelog with explicit breaking changes, what would you propose here? 

If it compiles, it's fine? Assume for a crate that high-profile we're fine?

**Comment by Nemo157** [comment]
There are definitely some breaking changes, specifically <https://docs.rs/hxgm30-client/0.3.0-alpha.01> will likely stop working since it has an invalid semver version. (I [found this crate](https://github.com/rust-lang/crates.io/issues/2463) previously when trying to make docs.rs more strict on semver).

I tried doing a local build of it to check that it just emits an error and doesn't panic anywhere, but modern `cargo` rejects its `Cargo.toml` so I can't. I can spend a little while checking our usage of `semver` to make sure it rejecting stuff in the database won't break other stuff.

I think this change should be fine assuming it doesn't break our assumptions, the versions that will become inaccessible don't work with modern cargo anyway.

**Comment by Nemo157** [comment]
https://github.com/rust-lang/docs.rs/blob/340dd46fd87460c27004e080159fa6e5f25071da/src/web/mod.rs#L338-L353

We may want to report an error and just skip the version here, so that one invalid version doesn't break finding the other valid versions.

---

https://github.com/rust-lang/docs.rs/blob/340dd46fd87460c27004e080159fa6e5f25071da/src/web/crate_details.rs#L259-L268

We're already skipping invalid versions here, but we could report an error too, so that we can delete any invalid versions we notice.

**Comment by syphar** [comment]
@Nemo157 should we perhaps put these general version-parsing changes into a separate PR? 

Should that one then be merged before this PR here?

**Comment by Nemo157** [comment]
Yep, doing that before-hand in a separate PR sounds like a good approach.

**Comment by syphar** [comment]
done in #1657

**Pull request closed without merging**
