### PR TITLE
Make search tab style match navigation

### PR DESCRIPTION
**Pull request by Zexbe**
1. Change the icon to use font awesome
2. Use the same border the other menu items are using

small

medium

large

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I guess you tried to use "fa-search" from font-awesome. Unfortunately, it doesn't work unless you add "font-family: FontAwesome" on the element. But then, the text would change as well. So not really ideal. :)

The border change looks good.

**Comment by Zexbe** [comment]
Oh no, I solved that issue. I lost the change somehow, one second.

**Comment by GuillaumeGomez** [comment]
Please add a screenshot too so people can see the changes.

**Comment by Zexbe** [comment]
Okay, I added pictures for three different media sizes.

**Comment by GuillaumeGomez** [comment]
Thanks! I'll merge once CI pass.

**Comment by pietroalbini** [comment]
Could you move the icon out of the placeholder so it's shown even when something is written in the input?

**Comment by Zexbe** [comment]
I'm not sure how I would make that work.
The icon would have to be all the way to the left, or right to keep it from moving as you typed.

**Comment by pietroalbini** [comment]
It'd be fine for me if the icon is all the way to the left.

**Comment by pietroalbini** [comment]
...and if we do that we could also left-align the input to make it less weird.

**Comment by Zexbe** [comment]
It would also be a button?

**Comment by Zexbe** [comment]
It is done, it looks even better now. I updated the pictures

**Comment by jyn514** [comment]
Any objections to merging?

**Comment by GuillaumeGomez** [comment]
Not from me. Let's wait for @pietroalbini's approval. ;)

**Comment by pietroalbini** [comment]
On the label add:

```css
label {
  cursor: pointer;
  padding-left: 0.5rem;
  font-size: 0.8em;
}
```
That way is more closely aligned with the rest of the items:

**Comment by Zexbe** [comment]
Okay, updated the search label

**Comment by pietroalbini** [comment]
Thanks!

**Pull request merged**
