### PR TITLE
Unify crate pages rendering

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
The result looks like this:

Screenshot from 2020-09-01 21-55-21
Screenshot from 2020-09-01 17-26-18
Screenshot from 2020-09-01 17-23-50
Screenshot from 2020-09-01 17-23-52

As you can see, we now keep the sidebar in all cases and there are no more weird tabs.

### CODE REVIEW

**Comment by jyn514** [comment]
I like this idea, but the top bar looks a little repetitive:

image

We should only show the title and clipboard once. Maybe we should remove it on the sidebar, so there's space to put the description below on the main page?

**Comment by jyn514** [comment]
> Maybe we should remove it on the sidebar

Hmm, then it wouldn't show up on `/builds` or `/source` though.

**Comment by Nemo157** [comment]
One big difference I notice with this is that the rustdoc pages are left-aligned, while this is centered, if your screen exceeds the max width.

Some more minor things (first two are already existing issues, but I found them more noticeable with this layout):
 - no indication of the current path when viewing a subfolder in source
 - no indication of the current file in "source"
 - big white page when looking at root/subfolder in "source"
 - white highlight of selected "builds" overlaps the bottom border of the dark panel
 - dark background of build log or file source merges with the dark panel of the sidebar, the "crate" page avoids this with a white gutter between the sidebar and the page contents

(It looks like existing ayu.rs styling does integrate well with it without any changes 😀)

**Comment by GuillaumeGomez** [comment]
Actually I removed the clipboard thing from the document and only kept it inside the sidebar (otherwise it duplicated an idea and made a test fail).

As for the points @Nemo157 reported, well, it's more or less already the case. But I'm open to ideas for improvement. :)

**Comment by Nemo157** [comment]
One other issue I just noticed is in the mobile rendering, before you get a row of icons, now you get a column of icons:

image

(mobile rendering is really not great as it stands, but it might make sense to fall back to the old layout if possible for it)

**Comment by GuillaumeGomez** [comment]
Forgot to check mobile, good point!

**Comment by GuillaumeGomez** [comment]
Now the mobile looks like this:

Screenshot from 2020-09-02 13-29-23

Not great, however I can suggest something similar to what we have in rustdoc: adding a burger button which will then display the menu.

**Comment by jyn514** [comment]
Actually I like the way you currently have it :) I don't think we should show a hamburger menu because most people are looking for the documentation, not /crate - we shouldn't make that harder to find.

**Comment by GuillaumeGomez** [comment]
Okay, I started something to check out how it looked but fine by me! However, I can keep the links and put the other information in the "hamburger menu"? That'd be a good middle thing.

**Comment by GuillaumeGomez** [comment]
Well, it can be done as a second step. Let's just focus on the sidebar for the moment. :)

**Review by jyn514 — APPROVED** [review]

**Pull request merged**
