### PR TITLE
Fix search background color on dark theme

### PR DESCRIPTION
**Pull request by pickfire**
Using firefox with dark theme.

Before

2019-09-28-102501_1366x768_scrot

After

2019-09-28-102513_1366x768_scrot

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I can't reproduce on my linux so I'll retry on another computer when I have time.

**Comment by pickfire** [comment]
@GuillaumeGomez I think you need to enable `widget.content.allow-gtk-dark-theme` in firefox.

I am using firefox 69 with breeze-dark as my system theme.

**Comment by GuillaumeGomez** [comment]
Oh I see! I'll give it another try then. Thanks for the tip!

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
