### PR TITLE
[WIP] Migrate to Tera for templating

### LINKED ISSUE #777: No link to builds tab on crate page
E.g. <https://docs.rs/crate/escargot/0.5.0> has no link to <https://docs.rs/crate/escargot/0.5.0/builds>, despite the latter having a "Builds" tab highlighted next to "Source".

### PR DESCRIPTION
**Pull request by Kixiron**
This is an attempt to both remove handlebars and add a type-safe interface to rendering templates while simultaneously making the templates more easy to modify and read.
Template reloading is also added via the very sketchy method of a thread that reloads the templates on 10s intervals, better solutions would be appreciated. (I tried to use `notify`, but it didn't work on my system even though it's supposed to)

Note: The templates are messy at times (currently), as I've pasted the navigation header into each and edited it to suit the current page, but after everything's done I'll squash them all together into something better
Note: The diff is massive right now because I moved the old `templates` folder, on the actual release the old templates will be deleted entirely

## Pages

- [x] `/` => `home_page.html`
- [x] `/about` => `about.html`
- [x] `/releases`, `/releases/failures`, `/releases/recent-failures`, `/releases/stars` => `releases.html`
- [x] `/releases/feed` => `release_feed.xml`
- [x] `/releases/queue` => `release_queue.html`
- [x] `/crate/:name` => `crate_details.html`
- [x] `/crate/:name/:version/builds` => `builds.html`
- [x] `/releases/activity` => `release_activity.html`
- [x] `/about/metrics` => Maybe N/A?
- [x] `/releases/:author`
- [x] `/crate/source`
- [x] rustdoc pages

## Possible Extensions

* Graph rendering can be done entirely in Tera as shown in [Drawing SVG Graphs with Rust](https://cetra3.github.io/blog/drawing-svg-graphs-rust/) and could be an alternative to Highcharts.js. This has the advantage of even less JavaScript, which makes it more accessible to users and gives us finer-grained control over our graphs, along with being self-sufficient (not relying on another service for part of our site) and not having the highcharts logo that currently exists there
* Add a footer with relevant info like the other Rust sites do
* Update `highlight.js` to the most recent version

Closes #777 and #740

### CODE REVIEW

**Comment by Kixiron** [comment]
Extra ideas: An extra field in the `[package.metadata.docs.rs]` section can be provided that allows uses to add extra syntax highlighting to their files, for example a C++ interop lib that has lots of example C++ code can put

```toml
[package.metadata.docs.rs]
extra_highlighting = ["cpp"]
```

in their Cargo.toml and we load the [C++ highlight script](https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/languages/cpp.min.js) with their crate. This can be extended further to partially or fully address #302 by offering a subset of further libraries that crates can selectively include

**Comment by jyn514** [comment]
> Template reloading is also added via the very sketchy method of a thread that reloads the templates on 10s intervals, better solutions would be appreciated. (I tried to use notify, but it didn't work on my system even though it's supposed to)

If notify doesn't work I would rather go without hot-reloadint for now.

**Comment by Kixiron** [comment]
In response to #777, I'm rewriting the templates anyways and it's actually less work to fix the issue because it's just a conditional that's in the header for some reason

**Comment by Kixiron** [comment]
Changes Breakdown:
  * `Page` is gone, long live `models`! Templates now correspond directly with a struct in [`src/web/page/models.rs`](https://github.com/rust-lang/docs.rs/pull/786/files#diff-e10c127185b5af59b696b5d143085aba), which makes templates type-safe, no more guessing if you've got parameters correct and changes are propagated to all call sites
  * All templates are cleanly split up into relevant directories and components, making it easier to add, read, remove and edit (as well as have a coherent theme)
  * `handlebars-iron` is no longer used as the templating engine of choice, as it has been replaced by [`tera`](https://github.com/rust-lang/docs.rs/pull/786/files#diff-80398c5faae3c069e4e6aa2ed11b28c0R54-R55)
  * `src/web/page/templates.rs` contains the [`TemplateData`](https://github.com/rust-lang/docs.rs/pull/786/files#diff-ee6431d852ce8913514eece9e3982d32R9-R19) struct which holds all loaded templates and any 'global' data that is relevant to all templates (Such as the [current version of docs.rs](https://github.com/rust-lang/docs.rs/pull/786/files#diff-ee6431d852ce8913514eece9e3982d32R113-R120) and [global alerts](https://github.com/rust-lang/docs.rs/pull/786/files#diff-ee6431d852ce8913514eece9e3982d32R105-R110))
  * `src/web/page/templates.rs` also contains some custom functions/filters for `tera` which allow more logic to be held in the templates themselves instead of the objects passed to them
  * Removed a lot of json tests, they aren't relevant since most everything now uses straight `serde` derives
  * `src/web/page/models.rs` contains all renderable structs along with the [`WebPage`](https://github.com/rust-lang/docs.rs/pull/786/files#diff-e10c127185b5af59b696b5d143085abaR13-R42) trait, which serves as an interface for cleanly manipulating them (e.g. [rendering](https://github.com/rust-lang/docs.rs/pull/786/files#diff-e10c127185b5af59b696b5d143085abaR16-R28), [getting the content type](https://github.com/rust-lang/docs.rs/pull/786/files#diff-e10c127185b5af59b696b5d143085abaR39-R41), etc)
  * `templates/base.html` is the base template from which all (excluding rustdoc) pages inherit, it pulls in style sheets, js and other resources as well as offering blocks where child templates can store data
  * `templates/crate` contains the [crate details](https://github.com/rust-lang/docs.rs/pull/786/files#diff-2550c2ab5e8909adfed2ffb04e746370), [builds](https://github.com/rust-lang/docs.rs/pull/786/files#diff-8acb2dba41e63189ab058c69bb8fb470) and [source pages](https://github.com/rust-lang/docs.rs/pull/786/files#diff-26a1ecce57cbc535a61c09a1a1a33aa9)
  * `templates/rustdoc` contains the [rustdoc pages](https://github.com/rust-lang/docs.rs/pull/786/files#diff-e735f89e8612284820c14924170cfca0) and [header](https://github.com/rust-lang/docs.rs/pull/786/files#diff-1c604723dd5137b7590266caefbb7b98)
  * `templates/releases` contains the [release queue](https://github.com/rust-lang/docs.rs/pull/786/files#diff-4d1dff01aa71f9baa6997ff894ffece0), [stars, recent releases, recent failures](https://github.com/rust-lang/docs.rs/pull/786/files#diff-9b79c8d1eab3f8a0ebb13bf6a086ca5d), etc. as well as the [XML release feed](https://github.com/rust-lang/docs.rs/pull/786/files#diff-22e184c148953123b0ff9e29fecbab4f)
  * `templates/header` contains the [header that appears on all pages](https://github.com/rust-lang/docs.rs/pull/786/files#diff-b1dca3ca8dc63516ce5d70b8670848dd), having the [builds/source/crate tabs](https://github.com/rust-lang/docs.rs/pull/786/files#diff-6c20631a35e5f8c8cba7c8e9ff227ad1) and [global alert](https://github.com/rust-lang/docs.rs/pull/786/files#diff-dfbc0991649c13c5df5d85be2083fab5) as separate components
  * `templates/docsrs` contains the docs.rs [landing page](https://github.com/rust-lang/docs.rs/pull/786/files#diff-dd22c77ca5b6fb7d53ba598570a3e9e8), [about page](https://github.com/rust-lang/docs.rs/pull/786/files#diff-94e675539da317dc1e279f48564dacb9) (with the [example `Cargo.toml`](https://github.com/rust-lang/docs.rs/pull/786/files#diff-d4d8db3fe278cd1a284862921c26125a) separate) and the [XML sitemap](https://github.com/rust-lang/docs.rs/pull/786/files#diff-4dca3d38f0e839e75af8325759c145c9)
  * The [`arc_swap`](https://github.com/rust-lang/docs.rs/pull/786/files#diff-80398c5faae3c069e4e6aa2ed11b28c0R57-R58) dependency was added to allow for [hot-reloading templates](https://github.com/rust-lang/docs.rs/pull/786/files#diff-ee6431d852ce8913514eece9e3982d32R40-R57) for development flows
  * The [`--reload`](https://github.com/rust-lang/docs.rs/pull/786/files#diff-a6d7191de78c3eab3986f02639fc5a43) option was added to the `start-web-server` command that activates template hot-reloading

The whole PR is heavily commented, so a lot of diff comes from that. Everything outside of `src/web/page/` and `templates/` is pretty much unchanged, it's just switching from using `Page` to using a different struct. Reviewing is probably easiest done by cloning this branch and running it locally before just browsing, everything should work identically to the currently running site

**Comment by Kixiron** [comment]
Laid the groundwork in #805

**Comment by Kixiron** [comment]
Finished by #887 (hopefully)

**Pull request closed without merging**
