### PR TITLE
Change layout to fix missing scrollbar highlighting (chromium text search)

### LINKED ISSUE #623: Search result positions not shown in chrome
The page content is contained in an element with the fixed css attribute. This causes the following result position indicators to not show up when searching:

### PR DESCRIPTION
**Pull request by cynecx**
Fixes #623.

This is more of a hack but I am not sure how a proper fix would look like.

### CODE REVIEW

**Comment by jyn514** [comment]
Will this bring back the issue mentioned in https://github.com/rust-lang/docs.rs/pull/510#issuecomment-562851135 ?

**Comment by cynecx** [comment]
@jyn514 I can't really reproduce the anchor issue?

**Comment by jyn514** [comment]
It was there a couple months ago, if it's not present in your PR that's a good sign.

r? @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I'm not sure to understand the connection between the remove code and the theme picker menu...

**Comment by cynecx** [comment]
@GuillaumeGomez Without it, it seems that the theme-picker is misaligned, why? I don’t really know, hence I have mentioned that this is more like a hack and not a proper fix.

I can’t really take screenshots now because I am not anywhere near a computer, but you can try out these changes directly in your browser and you will probably see what the issue is.

**Comment by GuillaumeGomez** [comment]
It's currently working for on my computer without those changes. So I'd definitely like to have screenshots. :)

**Comment by cynecx** [comment]
Patch without fix for theme-picker:

Screenshot from 2020-03-14 01-02-57

With theme-picker:

Screenshot from 2020-03-14 01-04-50

**Comment by GuillaumeGomez** [comment]
Ok, I confirm that your change doesn't break things on firefox and chrome. Thanks for the fix!

**Comment by cynecx** [comment]
Well, I think I broke it. I assume that this went already to production because it seems that I can reproduce the mentioned anchor issue. :thinking:

**Comment by GuillaumeGomez** [comment]
Did you try to empty the cache? Check if the CSS is the one from this PR to be sure it's yours too.

**Comment by cynecx** [comment]
@GuillaumeGomez Yes, in fact I have disabled it xD.

**Comment by GuillaumeGomez** [comment]
The new style is definitely there (tested on https://docs.rs/regex/1.3.5/regex/) and is working for me. You're sure your chromium is "fin"? :p

**Comment by cynecx** [comment]
Peek 2020-03-14 18-15

Firefox has the same behavior as Chromium. :/

**Comment by GuillaumeGomez** [comment]
Oh, that's what you meant! Yes, you definitely broke it. I completely forgot about the anchors...

**Comment by cynecx** [comment]
How should we proceed? I mean the trade off here doesn't seem that bad compared to losing the search highlighting functionality. 

Meanwhile: I am currently trying to find a workaround the fixed position of the sticky header.

**Comment by GuillaumeGomez** [comment]
No, the new behavior is worse. We need to find a way to fix the theme picker without breaking the anchors.

**Comment by cynecx** [comment]
Well, I guess it's a revert then. PR is coming right up.

**Pull request merged**
