### PR TITLE
 Fix `.env.sample` so it actually puts variables in the environment when sourced

### PR DESCRIPTION
**Pull request by notriddle**

### CODE REVIEW

**Comment by Nemo157** [comment]
Alternatively we could update the `.env.sample` to include `export` on every line. All dotfile loaders should support this (and a lot of them require it).

**Comment by syphar** [comment]
> Alternatively we could update the `.env.sample` to include `export` on every line. All dotfile loaders should support this (and a lot of them require it).

 Does docker-compose also support it?

**Comment by Nemo157** [comment]
Yep, I've had `export`s in my `.env` for ages and it works fine with docker-compose.

**Comment by syphar** [comment]
then to me, since many env-file loaders seem to need it, it would be more correct to update `.env.samle` to include `export`, together with updating the README.

**Review by syphar — APPROVED** [review]

**Pull request merged**
