### PR TITLE
Put back tab index on top crate search input

### LINKED ISSUE #118: Hide the search crate text field by default
Hi!

Some web plugins/web browsers have a shortcut to focus the first text field in a page, which is what I use in Rust documentations to start a search within the crate.
However, on docs.rs, there's another "Find crate" text field which is before the documentation search field which forbids me to use this shortcut.

So, it would be nice to hide the "Find crate" text field by default, requiring to click a button or hover to show the text field.
Another solution that would make it after the other text field would also fix this issue.

If you need help to implement that, I can contribute.

Thanks.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #118

### CODE REVIEW

**Comment by antoyo** [comment]
Can you add a comment to explain why we do this so that is does not get removed again in the future?

**Comment by GuillaumeGomez** [comment]
You mean in the HTML?

**Comment by antoyo** [comment]
It's a template, so it could be a template comment.

**Comment by GuillaumeGomez** [comment]
Yes, my bad for the incomplete answer. That's what I meant. ;)

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by jyn514** [comment]
This one fell through the cracks, sorry. Thanks for working on this!

**Comment by jyn514** [comment]
@antoyo I just deployed the change, do you mind visiting the site to see whether the problem is fixed?

**Comment by antoyo** [comment]
@jyn514: it works fine. Thanks.

**Pull request merged**
