### PR TITLE
upgrade crates-index-diff & gix

### PR DESCRIPTION
**Pull request by syphar**
- https://github.com/Byron/crates-index-diff-rs/releases/tag/v18.0.0
- https://github.com/Byron/crates-index-diff-rs/releases/tag/v19.0.0
- https://github.com/Byron/gitoxide/releases/tag/gix-v0.45.0
- https://github.com/Byron/gitoxide/releases/tag/gix-v0.46.0
- https://github.com/Byron/gitoxide/releases/tag/gix-v0.47.0

### CODE REVIEW

**Review by Byron — APPROVED** [review]
LGTM!

By the way, the next release is likely going to have `tracing` powered instrumentation if the feature it toggled on, which might be interesting for you in case you are already in the `tracing` ecosystem.

**Comment by Byron** [comment]
One more question though: the test-suite will perform fetches/clones of the index using `crates-index-diff`, right? It does have a new negotiation algorithm that I have applied a few fixes to. I believe these are released as well but I am not 100% sure.

If in doubt.let's keep this open with a reminder and wait for the next release, which isn't far out due to me wanting to release the `tracing` support.

**Comment by syphar** [comment]
> One more question though: the test-suite will perform fetches/clones of the index using `crates-index-diff`, right? It does have a new negotiation algorithm that I have applied a few fixes to. I believe these are released as well but I am not 100% sure.

@Byron yes, our build-tests would do fetches / clones. 

So you think we should wait for the next release?

**Comment by Byron** [comment]
It's coming in a few days, yes, let's wait to be certain the fixes are in. We can keep this PR open and adjust the versions.

**Comment by Byron** [comment]
And `crates-index-diff` v19 is now available: https://github.com/Byron/crates-index-diff-rs/releases/tag/v19.0.0 - this is the one to upgrade to.

**Comment by syphar** [comment]
@Byron I now updated `gix` to `0.47.0` and `crates-index-diff` to v19

**Review by Byron — APPROVED** [review]
LGTM!

**Pull request merged**
