### PR TITLE
Allow to click on the footer again by positioning the footer on top of the main div

### LINKED ISSUE #1599: Footer links not clickable
Steps to reproduce:

 1. Visit any recently built docs.rs page, e.g. https://docs.rs/rushterm/0.5.2/rushterm/.
 2. Scroll to the bottom of the page.
 3. Click "About docs.rs", "Privacy policy", or "Build queue".

Expected result: navigate somewhere else.

Actual result: no navigation.

Chrome 97.0.4692.71 (Official Build) (64-bit) on Linux.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #1599.

It'd be nice to start having GUI tests for docs.rs like rustdoc (with the same or a different GUI test framework, doesn't matter).

### CODE REVIEW

**Review by Nemo157 — APPROVED** [review]

**Review by syphar — CHANGES_REQUESTED** [review]
image

Testing I saw this issue here, now text seems to be behind the footer and I cannot reach it?

**Comment by Nemo157** [comment]
I don't get that issue testing on my server, the footer is against the bottom of the screen still on both variants of the rustdoc-css.

**Comment by syphar** [comment]
strange ... now I cannot reproduce it any more. All seems fine now.

**Comment by GuillaumeGomez** [comment]
@syphar Strange! If you find the problem again, please remember the page. ;)

**Comment by syphar** [comment]
will do so.

**Pull request merged**
