### PR TITLE
Add fonts to static folder

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Following discussion on #1146.

cc @pietroalbini @jyn514

### CODE REVIEW

**Comment by Nemo157** [comment]
The current static file handler doesn't actually support sub-directories afaik.

**Comment by GuillaumeGomez** [comment]
Strange, it worked perfectly fine locally.

**Comment by GuillaumeGomez** [comment]
I added the commit from #1158. :)

**Comment by GuillaumeGomez** [comment]
I moved everything back one level up (didn't squash the commit though, for now I want to keep the "history" haha).

**Review by Nemo157 — APPROVED** [review]
Tested locally and it's working well

**Pull request merged**
