### PR TITLE
Revert "The rest of Tera"

### PR DESCRIPTION
**Pull request by jyn514**
Reverts rust-lang/docs.rs#879

This caused many regressions. I will make a list of all we know of in the comments below.

cc @Kixiron

### CODE REVIEW

**Comment by jyn514** [comment]
500 internal errors on some pages:

```
Jul 07 21:22:18 docsrs cratesfyi[29806]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Msg("Failed to render \'rustdoc/page.html\'"), source: Some(Error { kind: Msg("Variable `dep[2]` not found in context while rendering \'rustdoc/navigation.html\': the evaluated version was `dep.2`. Maybe the index is out of bounds?"), source: None }) }', src/web/page/web_page.rs:36:24
Jul 07 21:23:50 docsrs cratesfyi[29806]:   14: cratesfyi::web::rustdoc::rustdoc_html_server_handler
```

Same error for crate_details:

```
Jul 07 21:23:53 docsrs cratesfyi[29806]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Msg("Failed to render \'crate/details.html\'"), source: Some(Error { kind: Msg("Variable `dep[2]` not found in context while rendering \'crate/details.html\': the evaluated version was `dep.2`. Maybe the index is out of bounds?"), source: None }) }', src/web/page/web_page.rs:36:24
```

**Comment by jyn514** [comment]
All builds were shown as failed, even if the documentation was available.

wrong-build-status

This is fixed by the following diff:

```diff
diff --git a/templates/crate/details.html b/templates/crate/details.html
index 1eeabf3..c1b6a3f 100644
--- a/templates/crate/details.html
+++ b/templates/crate/details.html
@@ -113,7 +113,7 @@
                                                 </a>
 
                                             {# If the release wasn't yanked and built correctly, display it normally #}
-                                            {%- elif release.build_status -%}
+                                            {%- elif not release.build_status -%}
                                                 <a href="/crate/{{ details.name }}/{{ release.version }}" class="pure-menu-link">
                                                     {{ release.version }}
                                                 </a>
diff --git a/templates/rustdoc/navigation.html b/templates/rustdoc/navigation.html
index 96275c0..7664f52 100644
--- a/templates/rustdoc/navigation.html
+++ b/templates/rustdoc/navigation.html
@@ -161,7 +161,7 @@
                                                                 </a>
 
                                                             {# If the release failed to build, display a warning #}
-                                                            {%- elif release.build_status -%}
+                                                            {%- elif not release.build_status -%}
                                                                 <a href="{{ release_url }}" class="pure-menu-link warn" title="docs.rs failed to build {{ release_name }}">
                                                                     <i class="fa fa-fw fa-warning"></i> {{ release.version }}
                                                                 </a>
```

**Comment by jyn514** [comment]
READMEs were shown as raw HTML instead of being rendered.

image

**Comment by Nemo157** [comment]
For https://docs.rs/actix-web-static-files/2.0.1/actix_web_static_files/index.html the non-rust codeblocks were having highlight.js styles applied, which clash badly with rustdoc dark styles. It looks like rustdoc applies the highlight.js language class, but doesn't actually load highlight.js to render it, but the new tera templates include highlight.js. I didn't get a screenshot, but should be easy to reproduce locally by building `actix-web-static-files 2.0.1`.

**Comment by Kixiron** [comment]
image

**Pull request merged**
