### PR TITLE
Update the favicon with a sharper, tuned version.

### PR DESCRIPTION
**Pull request by lgarron**
The new version keeps the style of the previous one uses the R from the Rust logo. It has been made slightly taller to be more clear at small resolution and given a clearer border for stronger constrast on varying backgrounds.

It contains 16x16 and 32x32 versions, rendered to show well on Retina as well non-Retina screens.

### CODE REVIEW

**Comment by lgarron** [comment]
Here are screenshots in both light and dark mode on macOS, for both Retina and non-Retina resolutions.

screenshots

They also include a version that keeps the R and its border a bit closer to the original, in case you would prefer that.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Looks good to me, thanks! I'll let someone with a mac confirm that it looks better before merging.

**Comment by lgarron** [comment]
> Looks good to me, thanks! I'll let someone with a mac confirm that it looks better before merging.

Thanks!

Just to be clarify, the icon should look snazzier on a variety of devices, I just happen to have macOS for testing.

**Review by syphar — APPROVED** [review]

**Comment by syphar** [comment]
LGTM, thanks!

**Pull request merged**
