### PR TITLE
run cargo update

### PR DESCRIPTION
**Pull request by syphar**
```
    Updating addr2line v0.20.0 -> v0.21.0
    Updating aho-corasick v1.0.3 -> v1.0.4
    Updating anyhow v1.0.72 -> v1.0.75
    Updating aws-smithy-async v0.56.0 -> v0.56.1
    Updating aws-smithy-checksums v0.56.0 -> v0.56.1
    Updating aws-smithy-client v0.56.0 -> v0.56.1
    Updating aws-smithy-eventstream v0.56.0 -> v0.56.1
    Updating aws-smithy-http v0.56.0 -> v0.56.1
    Updating aws-smithy-http-tower v0.56.0 -> v0.56.1
    Updating aws-smithy-json v0.56.0 -> v0.56.1
    Updating aws-smithy-protocol-test v0.56.0 -> v0.56.1
    Updating aws-smithy-query v0.56.0 -> v0.56.1
    Updating aws-smithy-runtime v0.56.0 -> v0.56.1
    Updating aws-smithy-runtime-api v0.56.0 -> v0.56.1
    Updating aws-smithy-types v0.56.0 -> v0.56.1
    Updating aws-smithy-types-convert v0.56.0 -> v0.56.1
    Updating aws-smithy-xml v0.56.0 -> v0.56.1
    Updating backtrace v0.3.68 -> v0.3.69
    Updating cc v1.0.82 -> v1.0.83
    Updating clap v4.3.21 -> v4.3.23
    Updating clap_builder v4.3.21 -> v4.3.23
    Updating crates-index v2.1.0 -> v2.1.1
    Updating dashmap v5.5.0 -> v5.5.1
    Updating deranged v0.3.7 -> v0.3.8
    Updating flate2 v1.0.26 -> v1.0.27
    Updating gimli v0.27.3 -> v0.28.0
    Updating gix v0.50.1 -> v0.51.0
    Updating gix-packetline v0.16.4 -> v0.16.5
    Updating gix-protocol v0.36.1 -> v0.37.0
    Updating h2 v0.3.20 -> v0.3.21
    Updating httpdate v1.0.2 -> v1.0.3
    Updating log v0.4.19 -> v0.4.20
    Updating object v0.31.1 -> v0.32.0
    Updating postgres v0.19.5 -> v0.19.6
    Updating postgres-derive v0.4.4 -> v0.4.5
    Updating postgres-protocol v0.6.5 -> v0.6.6
    Updating postgres-types v0.2.5 -> v0.2.6
    Updating prodash v25.0.1 -> v25.0.2
    Updating quote v1.0.32 -> v1.0.33
    Updating serde v1.0.183 -> v1.0.185
    Updating serde_derive v1.0.183 -> v1.0.185
    Updating serde_json v1.0.104 -> v1.0.105
    Updating slab v0.4.8 -> v0.4.9
    Updating syn v2.0.28 -> v2.0.29
    Updating tempfile v3.7.1 -> v3.8.0
    Updating thiserror v1.0.44 -> v1.0.47
    Updating thiserror-impl v1.0.44 -> v1.0.47
    Updating time v0.3.25 -> v0.3.27
    Updating time-macros v0.2.11 -> v0.2.13
    Updating tokio v1.30.0 -> v1.32.0
    Updating tokio-postgres v0.7.8 -> v0.7.9
    Updating unicase v2.6.0 -> v2.7.0
      Adding whoami v1.4.1
    Updating windows-targets v0.48.1 -> v0.48.5
    Updating windows_aarch64_gnullvm v0.48.0 -> v0.48.5
    Updating windows_aarch64_msvc v0.48.0 -> v0.48.5
    Updating windows_i686_gnu v0.48.0 -> v0.48.5
    Updating windows_i686_msvc v0.48.0 -> v0.48.5
    Updating windows_x86_64_gnu v0.48.0 -> v0.48.5
    Updating windows_x86_64_gnullvm v0.48.0 -> v0.48.5
    Updating windows_x86_64_msvc v0.48.0 -> v0.48.5
    Updating winreg v0.10.1 -> v0.50.0
```

### CODE REVIEW

**Comment by syphar** [comment]
the failing audit is solved in #2192

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by syphar** [comment]
( the test failure is odd, and I need to dig into it before merging this)

**Comment by Nemo157** [comment]
Probably related to https://github.com/seanmonstar/reqwest/pull/1898

**Comment by Nemo157** [comment]
We should probably disable emitting the BOM in `build.rs`: <https://docs.rs/grass/latest/grass/struct.Options.html#method.allows_charset>, according to <https://developer.mozilla.org/en-US/docs/Web/CSS/@charset> at least UTF-8 should be the default (if we want to be explicit we could add it to the `Content-Type` instead).

**Comment by syphar** [comment]
thanks for the hint @Nemo157 ! 

`allows_charset` didn't directly work, so I just downgraded `reqwest` for now to unblock this PR.

**Pull request merged**
