### PR TITLE
handle changed error responses from crates.io API

### PR DESCRIPTION
**Pull request by syphar**
Since Dec 18 we [were seeing errors when parsing search responses from crates.io](https://rust-lang.sentry.io/issues/4734684465/?environment=production&project=5499376&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=1), [deployed on the evening of Dec 16th](https://rust-lang.zulipchat.com/#narrow/stream/318791-t-crates-io/topic/deployments/near/408370216): 

> error decoding response body: missing field `crates` at line 1 column 47

grafik

Some digging lead me to [this crates.io change](https://github.com/rust-lang/crates.io/pull/7715) which changed the status code for errors, which lead to `error_for_status` not doing the early return.

### CODE REVIEW

**Comment by syphar** [comment]
fyi @Turbo87

**Comment by GuillaumeGomez** [comment]
Some tests broke but other than that, looks good to me.

**Comment by Turbo87** [comment]
sorry about that. it was ultimately a bug in crates.io that it did not comply with the interface description that cargo expects. it should hopefully be more consistent now, and once we switch the feature flag off there will be an official announcement blog post before we do so.

**Comment by syphar** [comment]
> sorry about that. it was ultimately a bug in crates.io that it did not comply with the interface description that cargo expects. it should hopefully be more consistent now, and once we switch the feature flag off there will be an official announcement blog post before we do so.

no worries, it's also on me that I didn't check how cargo itself handles the responses & errors :)

**Comment by syphar** [comment]
> Some tests broke but other than that, looks good to me.

@GuillaumeGomez 
the test failure is unrelated, re-running fixed it (I'll dig into this separately, looks like a race condition between the tests when run in parallel).

**Review by GuillaumeGomez — APPROVED** [review]

**Pull request merged**
