### PR TITLE
Improve warnings display

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
ayu:

Screenshot from 2020-10-27 16-36-04

dark:

Screenshot from 2020-10-27 16-46-07

### CODE REVIEW

**Comment by Nemo157** [comment]
Does this affect the "not latest version" warning too? Can we get screenshots of that?

**Comment by GuillaumeGomez** [comment]
Good point, checking!

**Comment by jyn514** [comment]
Default color: 
image
Color with hover: 
hover

We might want to make the color without hover a yellow?

**Comment by GuillaumeGomez** [comment]
For me it's yellow/orange by default?

**Comment by GuillaumeGomez** [comment]
Ah no you're right! Since we changed the color in the display, it's the same in the topbar haha. So this'll be the same problem for ayu. Need to think about that...

**Comment by GuillaumeGomez** [comment]
Updated!

**Comment by jyn514** [comment]
The warnings look a lot better :)

image
image
image
image

**Pull request merged**
