### PR TITLE
Fixes #1267 - fix handling of github graphql errors

### LINKED ISSUE #1267: github backfill cannot skip not found repositories any more
While testing for #1249 I stumbled on errors while backfilling the github repos. 

Error is: 
```
Error: error decoding response body: missing field `path` at line 1 column xxx
```
[in a place where we actually filter out the `NOT_FOUND` errors to gracefully handle them.](https://github.com/rust-lang/docs.rs/blob/9fe8f02bdbfa6f99de7f9340498bbdac588a5183/src/utils/github_updater.rs#L145-L156) 

I do know for that all the failures I saw that the repo didn't exist, but I don't know the exact response (yet), so which error it really is. 

full backtrace
```

Stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/syphar/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.48/src/backtrace/libunwind.rs:86
      backtrace::backtrace::trace_unsynchronized
             at /Users/syphar/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.48/src/backtrace/mod.rs:66
   1: backtrace::backtrace::trace
             at /Users/syphar/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.48/src/backtrace/mod.rs:53
   2: backtrace::capture::Backtrace::create
             at /Users/syphar/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.48/src/capture.rs:164
   3: backtrace::capture::Backtrace::new_unresolved
             at /Users/syphar/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.48/src/capture.rs:158
   4: failure::backtrace::internal::InternalBacktrace::new
             at /Users/syphar/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/backtrace/internal.rs:46
   5: failure::backtrace::Backtrace::new
             at /Users/syphar/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/backtrace/mod.rs:121
   6: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from
             at /Users/syphar/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/error/error_impl.rs:19
   7: <failure::error::Error as core::convert::From<F>>::from
             at /Users/syphar/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.8/src/error/mod.rs:36
   8: docs_rs::utils::github_updater::GithubUpdater::graphql
             at src/utils/github_updater.rs:245
   9: docs_rs::utils::github_updater::GithubUpdater::load_repository
             at src/utils/github_updater.rs:138
  10: docs_rs::utils::github_updater::GithubUpdater::backfill_repositories
             at src/utils/github_updater.rs:108
  11: cratesfyi::DatabaseSubcommand::handle_args
             at src/bin/cratesfyi.rs:434
  12: cratesfyi::CommandLine::handle_args
             at src/bin/cratesfyi.rs:132
  13: cratesfyi::main
             at src/bin/cratesfyi.rs:21
  14: core::ops::function::FnOnce::call_once
             at /Users/syphar/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /Users/syphar/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125
  16: std::rt::lang_start::{{closure}}
             at /Users/syphar/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:66
  17: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:259
      std::panicking::try::do_call
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381
      std::panicking::try
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345
      std::panic::catch_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396
      std::rt::lang_start_internal
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:51
  18: std::rt::lang_start
             at /Users/syphar/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:65
  19: _main
```

### PR DESCRIPTION
**Pull request by syphar**
After #1249 was merged, I just updated this bugfix here. 

General GitHub errors, especially `RATE_LIMITED` come without `data` element, and without `path` in the error. 

This PR makes `GraphResponse.data` an `Option`, and adds `#[serde(default)]` to the `path` on the `GraphError`. 

With this we can handle the `RATE_LIMITED` error the same way as our "soft" rate limit error (configured with `Config.github_updater_min_rate_limit`). 

Of course the actual impact of this is quite low right now, that might only change with vastly more crates / repos, when the hourly repo-update will have too many repos.

### CODE REVIEW

**Comment by syphar** [comment]
backfill test is still running on my machine. 

That part is not (yet) covered in tests. 

If the structure gets added soonish in #1249 , I'll wait with this PR for the structure and then add tests for this. 


The method fixed is `GithubUpdater.load_repository`, which means the problem can happen also for new crates (while it's less likely for a new crate to have an invalid github url)

**Comment by jyn514** [comment]
I think it might be nice to land the tests before landing the refactors in #1249.

**Comment by syphar** [comment]
@jyn514 that's exactly what I was planning, see the PR description: 

> Because this conflicts with #1249 , I would leave this for now, and add the fix + some tests after the refactor was merged (cc @GuillaumeGomez ).

**Comment by syphar** [comment]
@jyn514 I updated (actually redid) this PR, IMHO we could review it too

**Comment by jyn514** [comment]
> With this we can handle the RATE_LIMITED error the same way as our "soft" rate limit error (configured with Config.github_updater_min_rate_limit).

Is there a way to test this? Maybe by setting the rate limit to something high?

**Comment by syphar** [comment]
> > With this we can handle the RATE_LIMITED error the same way as our "soft" rate limit error (configured with Config.github_updater_min_rate_limit).
> 
> Is there a way to test this? Maybe by setting the rate limit to something high?

I could reproduce it locally when running a backfill on a database with all releases, but no repos. That's where I got the JSON payload from that I have in the tests.

**Review by jyn514 — APPROVED** [review]

**Pull request merged**
