### PR TITLE
Replace version with "latest" in the URL.

### PR DESCRIPTION
**Pull request by linyihai**
This is an enhancement from: https://github.com/rust-lang/docs.rs/issues/1691

it will replace the latest version with "latest" in the URL, like 
-  /serde/latest/serde
-  /crate/regex/latest

### CODE REVIEW

**Review by syphar — CHANGES_REQUESTED** [review]
Thank you for the help! 

Looking at #1691 , the request was actually _only_ for the search results ([this page](https://docs.rs/releases/search?query=axum)), 

[The normal release-pages](https://docs.rs/releases) should stay specific to the releases / versions. 

This might mean that the search-result template can't use the releases-base any more, or the structure has to be slightly changed.

**Comment by linyihai** [comment]
> Thank you for the help!
> 
> Looking at #1691 , the request was actually _only_ for the search results ([this page](https://docs.rs/releases/search?query=axum)),
> 
> [The normal release-pages](https://docs.rs/releases) should stay specific to the releases / versions.
> 
> This might mean that the search-result template can't use the releases-base any more, or the structure has to be slightly changed.

Sounds Good.  I will make a improvement on it.

**Comment by linyihai** [comment]
I notice a `release_type` variable in releases template,  it will be resonable to untilize it to confirm the search results.

**Review by syphar — APPROVED** [review]

**Comment by syphar** [comment]
thank you for this! 

note that we still have manual deploys, which I do at least roughly once a week

**Pull request merged**
