### PR TITLE
Remove whitespace beside docs.rs text

### PR DESCRIPTION
**Pull request by pickfire**
Last time I removed whitespace somewhere else, this time in menu.

Re-fix #1160 

r? @jyn514

### CODE REVIEW

**Comment by pickfire** [comment]
I wonder if there is some sort of templating that automatically removes all these unnecessary whitespaces.

**Comment by jyn514** [comment]
Can you post a screenshot of the issue this is fixing?

**Comment by pickfire** [comment]
https://github.com/Keats/tera/pull/430/files maybe we could use `{{-`? Not sure if `{%-` is doing what I think it is.

**Comment by pickfire** [comment]
Should be the same as the old one since I probably remove another whitespace last time.

image

**Comment by jyn514** [comment]
Seems fine, then.

**Comment by pickfire** [comment]
How long does it take for the change to be reflected in the current docs.rs?

**Comment by jyn514** [comment]
@pickfire the deployments are irregular; 'when I find time for it'. For smaller PRs I usually wait until a few larger ones land, since each deployment has about 10 seconds of downtime until we fix https://github.com/rust-lang/docs.rs/issues/1150.

**Pull request merged**
