### PR TITLE
 Standardize environment variables on DOCSRS_

### PR DESCRIPTION
**Pull request by jyn514**
This changes the following env variables used in prod:

- CRATESFYI_PREFIX
- CRATESFYI_DATABASE_URL
- CRATESFYI_GITHUB_ACCESSTOKEN
- CRATESFYI_RUSTWIDE_WORKSPACE
- CRATESFYI_TOOLCHAIN
- DOCS_RS_BUILD_CPU_LIMIT

Before deploying, we should set the new names of all these variables.
After deploying, we can delete the old names.

Helps with https://github.com/rust-lang/docs.rs/issues/244.

### CODE REVIEW

**Comment by jyn514** [comment]
@pietroalbini do you have time to review this?

**Comment by pietroalbini** [comment]
I'm wondering if we should have some code that errors out if the old environment variables are present, pointing to the new ones. That would help with people's local development environments, especially ones that are used occasionally.

**Comment by jyn514** [comment]
@pietroalbini we can't do that until this is deployed because the production server needs to be able to switch between the two, there's no way to switch the environment and update the code at the same time currently. Happy to turn it into a hard error in a future PR.

**Comment by pietroalbini** [comment]
Sure, sounds good to have it in a followup PR!

**Pull request merged**
