### PR TITLE
Transfer to 2018 edition

### PR DESCRIPTION
**Pull request by lzutao**
Rustfmt PR next.

### CODE REVIEW

**Comment by lzutao** [comment]
Rebased on master.

**Comment by QuietMisdreavus** [comment]
I'm generally on board with the spirit of this and https://github.com/rust-lang/docs.rs/pull/339, but i'm about to merge several PRs to docs.rs, so once that's done we can rebase one final time and i can turn to this.

**Comment by lzutao** [comment]
Ping. Do anythings else block this?

**Comment by pickfire** [comment]
Any news on this?

**Comment by svenstaro** [comment]
This needs a rebase.

**Comment by lzutao** [comment]
I know. But the project maintainers do not have interest in this PR. Maybe I should 
close this PR.

**Pull request closed without merging**
