### PR TITLE
fix serving custom CSS coming from --extend-css in rustdoc

### LINKED ISSUE #2524: Custom CSS from `--extend-css` doesn't work
I have a Rust repo at https://github.com/hedgetechllc/musicxml that contains a Rust workspace and 3 sub-projects. To build the docs for the main project (musicxml) to include the contents of a custom CSS file at `musicxml/assets/docs.css`, I can either run from either the root workspace directory or the `musicxml` directory:

`RUSTDOCFLAGS="--extend-css musicxml/assets/docs.css" cargo doc --no-deps`

And everything works fine.

I added the following to the `Cargo.toml` file in the `musicxml` directory so that docs.rs would pass the appropriate RUSTDOCFLAGS when building:

```
[package.metadata.docs.rs]
rustdoc-args = ["--extend-css", "musicxml/assets/docs.css"]
```

However, this resulted in a build error on docs.rs about `musicxml/assets/docs.css` not existing. I figured this was probably because the full workspace wasn't being passed to docs.rs and just the `musicxml` project itself, so I updated the `Cargo.toml` file to read:

```
[package.metadata.docs.rs]
rustdoc-args = ["--extend-css", "assets/docs.css"]
```

...and this caused the docs to build without problem on docs.rs; however, the CSS changes still weren't showing in the docs, and upon inspecting the source code, I can see that the CSS stylesheet is being added as:

```
<link rel="stylesheet" href="../theme-20240617-1.81.0-nightly-59e2c01c2.css">
```

...referencing a parent directory `..` that doesn't seem to exist on docs.rs. Is this a bug, or am I somehow using the wrong `--extend-css` flag to get this CSS file to populate correctly. I do a similar manual process on GitHub, and the docs generate just fine there. Thanks!

### PR DESCRIPTION
**Pull request by syphar**
Resolves #2524 

The CSS content from `--extend-css` ends up in a `theme.css` in the rustdoc output. 

We have to serve these similar to invocation specific JS files. 

I added a test testing for both custom JS & CSS files, also validated locally that the bug in #2524 is fixed

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
I thought this case was handled already. Good catch!

**Comment by hedgecrw** [comment]
Thanks for the quick fix everyone! One quick question/request...is there a way to manually trigger a re-build of the current docs for a release, or will I need to just up the version number and republish to take advantage of this fix?

**Comment by syphar** [comment]
It's actually option 3 : 

We still only manually deploy docs.rs, which is why we have this "waiting for deploy" label. 

I'll probably do a deploy tomorrow or the day after, then everything should directly be fine.

**Comment by hedgecrw** [comment]
Perfect, thanks again

**Comment by syphar** [comment]
@hedgecrw the code is deployed, everything should work now, can you confirm?

**Comment by hedgecrw** [comment]
I can confirm that everything now looks correct.

**Pull request merged**
