### PR TITLE
Show message that doc comment is too long instead of failing

### PR DESCRIPTION
**Pull request by kyrias**
Fixes at least <https://github.com/onur/docs.rs/issues/23#issuecomment-414062152>.

### CODE REVIEW

**Comment by kyrias** [comment]
For the record, I was considering just returning `None` instead, but I figured it might help any confused crate author figure out what is causing it to be missing.

**Comment by kyrias** [comment]
@onur Ping?

**Comment by kyrias** [comment]
Ping?

**Comment by onur** [comment]
opps sory @kyrias forgot about this one, thanks for the patch!

**Comment by kyrias** [comment]
No problem, thanks for maintaining this awesome project!

**Pull request merged**
