### PR TITLE
Run `cargo update`

### PR DESCRIPTION
**Pull request by jyn514**
This will reduce the size of the diff in #709 considerably. Additionally, if we have to revert the PR it will be easier to find what caused the failure.

<details><summary>Changes</summary>

```
   Updating crates.io index
    Updating adler32 v1.0.3 -> v1.0.4
    Updating aho-corasick v0.6.8 -> v0.6.10
    Removing antidote v1.0.0
    Updating approx v0.3.0 -> v0.3.2
    Updating arc-swap v0.3.11 -> v0.4.5
    Removing argon2rs v0.2.5
    Updating arrayref v0.3.5 -> v0.3.6
    Updating arrayvec v0.4.7 -> v0.5.1
    Updating atty v0.2.11 -> v0.2.14
    Updating backtrace v0.3.9 -> v0.3.46
    Updating backtrace-sys v0.1.24 -> v0.1.35
      Adding base64 v0.11.0
    Removing blake2-rfc v0.2.18
      Adding blake2b_simd v0.5.10
    Updating bytesize v0.1.3 -> v1.0.0
    Removing c2-chacha v0.2.3
    Updating chrono v0.4.7 -> v0.4.11
    Updating constant_time_eq v0.1.3 -> v0.1.5
      Adding cookie v0.12.0
      Adding cookie_store v0.7.0
    Updating core-foundation v0.5.1 -> v0.7.0
    Updating core-foundation-sys v0.5.1 -> v0.7.0
      Adding crossbeam-queue v0.1.2
    Updating crossbeam-utils v0.5.0 -> v0.6.6
    Updating derive_more v0.99.2 -> v0.99.5
    Updating dtoa v0.4.3 -> v0.4.5
    Updating encoding_rs v0.8.10 -> v0.8.22
      Adding error-chain v0.12.2
    Updating failure v0.1.5 -> v0.1.7
    Updating failure_derive v0.1.5 -> v0.1.7
    Updating fallible-iterator v0.1.5 -> v0.1.6
    Updating filetime v0.2.1 -> v0.2.9
    Updating flate2 v1.0.3 -> v1.0.14
    Updating futures v0.1.25 -> v0.1.29
    Updating getrandom v0.1.12 -> v0.1.14
    Updating git2 v0.13.0 -> v0.13.2
      Adding hermit-abi v0.1.10
    Updating httparse v1.3.3 -> v1.3.4
    Updating hyper v0.10.13 -> v0.10.16
    Updating hyper-tls v0.3.1 -> v0.3.2
    Updating indexmap v1.0.1 -> v1.3.2
    Updating iovec v0.1.2 -> v0.1.4
    Updating itoa v0.4.3 -> v0.4.5
    Removing lazycell v1.2.0
    Updating libc v0.2.62 -> v0.2.68
    Removing libflate v0.1.27
    Updating libgit2-sys v0.12.0+0.99.0 -> v0.12.3+1.0.0
    Updating libz-sys v1.0.24 -> v1.0.25
    Updating lock_api v0.1.4 -> v0.3.4
    Updating memoffset v0.5.3 -> v0.5.4
    Updating mime v0.3.9 -> v0.3.16
    Removing mime_guess v1.8.6
    Removing mime_guess v2.0.1
      Adding mime_guess v1.8.8
      Adding mime_guess v2.0.3
    Removing miniz-sys v0.1.10
      Adding miniz_oxide v0.3.6
    Updating mio v0.6.16 -> v0.6.21
    Updating native-tls v0.2.1 -> v0.2.4
    Updating new_debug_unreachable v1.0.1 -> v1.0.4
    Updating nix v0.11.0 -> v0.11.1
    Updating nodrop v0.1.12 -> v0.1.14
    Updating num-integer v0.1.39 -> v0.1.42
    Updating num-iter v0.1.37 -> v0.1.40
    Updating num-traits v0.2.6 -> v0.2.11
    Updating num_cpus v1.8.0 -> v1.12.0
    Updating once_cell v1.2.0 -> v1.3.1
    Updating openssl v0.10.13 -> v0.10.29
    Updating openssl-sys v0.9.45 -> v0.9.55
    Updating ordered-float v1.0.1 -> v1.0.2
    Removing owning_ref v0.3.3
    Removing parking_lot v0.6.4
      Adding parking_lot v0.9.0
      Adding parking_lot v0.10.2
    Removing parking_lot_core v0.3.1
      Adding parking_lot_core v0.6.2
      Adding parking_lot_core v0.7.1
    Updating phf v0.7.21 -> v0.7.24
    Updating phf_codegen v0.7.21 -> v0.7.24
    Updating phf_generator v0.7.21 -> v0.7.24
    Updating phf_shared v0.7.21 -> v0.7.24
    Updating pkg-config v0.3.14 -> v0.3.17
    Updating postgres-shared v0.4.1 -> v0.4.2
    Updating proc-macro-hack v0.5.11 -> v0.5.15
    Removing proc-macro2 v0.3.8
    Removing proc-macro2 v0.4.20
    Removing proc-macro2 v1.0.6
      Adding proc-macro2 v0.4.30
      Adding proc-macro2 v1.0.10
      Adding publicsuffix v1.5.4
    Updating quick-error v1.2.2 -> v1.2.3
    Removing quote v0.5.2
    Removing quote v0.6.8
      Adding quote v0.6.13
    Updating r2d2 v0.8.2 -> v0.8.8
    Removing rand v0.3.22
    Removing rand v0.4.3
    Removing rand v0.5.5
      Adding rand v0.3.23
      Adding rand v0.4.6
      Adding rand v0.6.5
    Removing rand_chacha v0.2.1
      Adding rand_chacha v0.1.1
      Adding rand_chacha v0.2.2
    Removing rand_core v0.2.2
    Removing rand_core v0.3.0
    Removing rand_core v0.4.0
      Adding rand_core v0.3.1
      Adding rand_core v0.4.2
      Adding rand_hc v0.1.0
      Adding rand_isaac v0.1.1
      Adding rand_jitter v0.1.4
      Adding rand_pcg v0.1.2
      Adding rand_xorshift v0.1.1
    Updating redox_syscall v0.1.40 -> v0.1.56
    Removing redox_termios v0.1.1
    Updating redox_users v0.3.0 -> v0.3.4
    Updating reqwest v0.9.2 -> v0.9.24
    Removing rle-decode-fast v1.0.1
    Updating route-recognizer v0.1.12 -> v0.1.13
      Adding rust-argon2 v0.7.0
    Updating rustc-demangle v0.1.9 -> v0.1.16
    Removing rusttype v0.7.2
      Adding rusttype v0.7.9
      Adding rusttype v0.8.3
    Removing ryu v0.2.6
    Updating safemem v0.3.0 -> v0.3.3
    Updating same-file v1.0.4 -> v1.0.6
    Updating sass-rs v0.2.1 -> v0.2.2
    Updating sass-sys v0.4.7 -> v0.4.19
    Updating schannel v0.1.14 -> v0.1.18
    Updating scheduled-thread-pool v0.2.0 -> v0.2.4
    Updating schemamama_postgres v0.2.3 -> v0.2.4
    Removing scoped_threadpool v0.1.9
    Removing scopeguard v0.3.3
    Removing scopeguard v1.0.0
      Adding scopeguard v1.1.0
    Updating security-framework v0.2.1 -> v0.4.2
    Updating security-framework-sys v0.2.1 -> v0.4.2
    Updating serde v1.0.104 -> v1.0.106
    Updating serde_derive v1.0.104 -> v1.0.106
    Updating serde_json v1.0.32 -> v1.0.51
    Updating serde_urlencoded v0.5.3 -> v0.5.5
    Removing signal-hook v0.1.9
    Updating signal-hook-registry v1.0.1 -> v1.2.0
    Updating siphasher v0.3.1 -> v0.3.2
    Updating slab v0.4.1 -> v0.4.2
    Updating smallvec v1.2.0 -> v1.3.0
    Updating socket2 v0.3.8 -> v0.3.12
    Updating stb_truetype v0.2.4 -> v0.3.1
    Updating string_cache v0.7.3 -> v0.7.5
    Updating string_cache_codegen v0.4.1 -> v0.4.4
    Removing syn v0.15.11
    Removing syn v1.0.11
      Adding syn v0.15.44
      Adding syn v1.0.17
    Updating synstructure v0.10.0 -> v0.12.3
    Updating systemstat v0.1.4 -> v0.1.5
    Removing take_mut v0.2.2
    Updating tar v0.4.20 -> v0.4.26
    Updating tempfile v3.0.4 -> v3.1.0
    Updating tendril v0.4.0 -> v0.4.1
    Updating termcolor v1.0.4 -> v1.1.0
    Removing termion v1.5.1
    Updating time v0.1.40 -> v0.1.42
    Updating tokio-codec v0.1.1 -> v0.1.2
    Updating tokio-io v0.1.9 -> v0.1.13
    Updating tokio-process v0.2.3 -> v0.2.5
    Updating tokio-reactor v0.1.6 -> v0.1.12
    Updating tokio-signal v0.2.7 -> v0.2.9
    Updating tokio-tcp v0.1.2 -> v0.1.4
    Updating tokio-udp v0.1.2 -> v0.1.6
    Updating toml v0.5.5 -> v0.5.6
      Adding try_from v0.3.2
    Updating typed-arena v1.4.1 -> v1.7.0
    Updating typenum v1.10.0 -> v1.11.2
    Updating ucd-util v0.1.1 -> v0.1.8
    Updating unicode-normalization v0.1.7 -> v0.1.12
    Updating unicode-width v0.1.5 -> v0.1.7
    Removing unreachable v1.0.0
    Updating url v1.7.1 -> v1.7.2
    Updating utf-8 v0.7.4 -> v0.7.5
    Updating utf8-ranges v1.0.1 -> v1.0.4
    Updating uuid v0.7.1 -> v0.7.4
    Updating vcpkg v0.2.6 -> v0.2.8
    Updating wasi v0.7.0 -> v0.9.0+wasi-snapshot-preview1
    Updating winapi v0.3.6 -> v0.3.8
    Updating winapi-util v0.1.2 -> v0.1.4
    Removing wincolor v1.0.1
      Adding winreg v0.6.2
```

</details>

cc @Kixiron 
r? @Mark-Simulacrum

### CODE REVIEW

**Comment by jyn514** [comment]
Hmm, this added a dependency on iron 0.6 through param 0.8. I'll see if I can get rid of that.

**Comment by Mark-Simulacrum** [comment]
Hm, so I thought we had already tried this and it broke things? Do we believe that's now been fixed with the html5ever/kuchiki work?

**Comment by Mark-Simulacrum** [comment]
If so, feel free to merge, I guess, though we should monitor afterwards.

**Comment by jyn514** [comment]
Yes, I never tried it on its own, only in conjunction with the html5ever update. Hopefully this will not have a impact, I'm running the html benchmark now but I don't think we have any other benchmarks.

**Comment by jyn514** [comment]
I fixed the build failure. I don't have time to monitor right now, hopefully I'll get a chance sometime this afternoon.

**Comment by jyn514** [comment]
Before:

```parse regex html        time:   [10.184 ms 10.202 ms 10.223 ms]
                        change: [-0.2705% +0.0487% +0.3441%] (p = 0.76 > 0.05)
                        No change in performance detected.
```

After:
```
parse regex html        time:   [10.107 ms 10.126 ms 10.149 ms]
                        change: [-0.3788% -0.1075% +0.1827%] (p = 0.45 > 0.05)
                        No change in performance detected.
Found 21 outliers among 100 measurements (21.00%)
  1 (1.00%) low mild
  17 (17.00%) high mild
  3 (3.00%) high severe
```

So no noticable difference.

**Pull request merged**
