### PR TITLE
Add anchor-workaround for 'small-section-header' and method heading

### PR DESCRIPTION
**Pull request by cynecx**
See https://github.com/rust-lang/docs.rs/pull/637#issuecomment-599148480.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Just tried this: https://docs.rs/regex/1.3.5/regex/struct.Matches.html#impl-Borrow%3CT%3E

Doesn't look very nice, but it's not from this change. Otherwise, this PR makes things a bit better. So I'm find with merging it. Your call @jyn514. :)

**Comment by cynecx** [comment]
@GuillaumeGomez Ehrm, it kinda looks "normal" to me. Do you mind taking a screenshot for me?

**Comment by GuillaumeGomez** [comment]
With this PR, it gives (on firefox):

Screenshot from 2020-03-16 18-44-34

**Comment by jyn514** [comment]
That looks like it still has the anchor issue to me. The prod version running right now has the same issue.

**Comment by cynecx** [comment]
I've just checked that out and it seems like this trick won't work with impl headings because the styling for `<h3>` uses `display: flex`. I honestly don't know what we can do here except use a wrapper element so `display: flex` doesn't affect the `::before`-pseudoelement.

**Comment by GuillaumeGomez** [comment]
I still think that pushing all the content under the docs.rs top banner is the best solution.

**Comment by jyn514** [comment]
> I still think that pushing all the content under the docs.rs top banner is the best solution.

The problem with this is that `overflow: auto` seems to cause lots of other issues. I don't know CSS very well but @cormacrelf said in https://github.com/rust-lang/docs.rs/issues/595#issue-561499035 that `fixed` causes lots of problems on mobile.

**Comment by GuillaumeGomez** [comment]
If this is mobile only, then we can implement mobile-specific fixes.

**Comment by cynecx** [comment]
Honestly, I feel bad :/. Introducing that PR which allowed better chromium search experience doesn't really justify the broken things right now.

> I still think that pushing all the content under the docs.rs top banner is the best solution.

Do you mean not having a sticky header at all?

**Comment by jyn514** [comment]
> Honestly, I feel bad :/

Oh don't worry, the CSS has been broken long before you started making changes 😆. We might end up reverting your change though.

**Comment by cynecx** [comment]
@jyn514 Yes I kinda agree, I thought this could have worked by apply various fixes here and there but this requires a more “thorough” rework/redesign (probably starting with rustdoc) I guess.

If @GuillaumeGomez agrees too, I would close this PR and revert all the changes related to this and perhaps open a new tracking issue.

**Comment by GuillaumeGomez** [comment]
> Do you mean not having a sticky header at all?

Yes and no. Depends how we do it. If we make the whole content start below the header, it won't go under it.

**Comment by jyn514** [comment]
> If @GuillaumeGomez agrees too, I would close this PR and revert all the changes related to this and perhaps open a new tracking issue.

Ok, please do this.

**Comment by jyn514** [comment]
> @jyn514 Yes I kinda agree, I thought this could have worked by applying various fixes here and there but this requires a more “thorough” rework/redesign (probably starting with rustdoc) I guess.

Note that we cannot change the generated HTML on past documentation. Doing so would at a minimum take several months of compute time, and might also cause builds to fail that previously passed. See https://github.com/rust-lang/docs.rs/issues/464.

**Comment by GuillaumeGomez** [comment]
No need to change the HTML, just overload the CSS with our own.

**Pull request closed without merging**
