### PR TITLE
Adds a button to copy the code to the clipboard - index.js

### PR DESCRIPTION
**Pull request by grey4owl**
A very simple button that was missing in the upper right corner to copy the example code to the clipboard. I wasn't sure where to put the CSS so I added it directly to the element with js..

Screenshot from 2024-01-12 20-08-22

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
So if I understand correctly, you want it for code examples in rustdoc pages, right? If so it's not the right place to do this. Please instead open an issue on `rust-lang/rust`. I prefer to warn: this is a very tricky UI change because it can be done in a lot of different ways. For example, your implementation cannot be used on mobile devices, although they're the ones where you'd want to use this feature the most.

For it to work on mobile devices, the button would need to be displayed all the time. Then comes the fun part: should it be put above the code example or hovering the code example with the risk of hiding code beneath it?

**Comment by syphar** [comment]
I wasn't sure if the examples came from the README file, which would mean we would have to look at our own docs.rs markdown renderer. But the screenshot above _looks_ like it's from `clap`, where I don't find any examples. 

So yes, if it's examples from the documentation pages, the way to do is to add this new (very useful IMO!) feature to rustdoc itself.

**Comment by syphar** [comment]
@grey4owl can you provide an example link to which examples are you talking about? Is it readme or documentation?

**Comment by grey4owl** [comment]
I was talking about any code blocks (`<div class="example-wrap">` ) elements found in the documentation of all crates.io packages, but you are right, this should be added to the rustdoc directly so i will move this there.. Sorry :smiling_face_with_tear:

**Comment by syphar** [comment]
> I was talking about any code blocks (`<div class="example-wrap">` ) elements found in the documentation of all crates.io packages, but you are right, this should be added to the rustdoc directly so i will move it there.. Sorry 🥲

no worries, nothing to be sorry about. It can be complex to navigate the components and their connections. 

Can you link the new issue here so I can follow it?

**Pull request closed without merging**
